package oxml

import (
	"encoding/xml"

	xmlb "github.com/mgilbir/spine/common/xml"
)

// ---------------------------------------------------------------------------
// Pivot table definition part (xl/pivotTables/pivotTableN.xml).
//
// CT_PivotTableDefinition models the pivot table layout: which cache fields sit
// on the row, column, value (data) and page (filter) axes, and each value
// field's aggregation. Read (ParsePivotTableDefinition) is lenient and decodes
// only what the public API exposes; pivot parts from an opened workbook
// round-trip verbatim among the preserved parts. Write
// (MarshalPivotTableDefinition) serializes a pivot created via
// Sheet.AddPivotTable into a fresh, canonical part; the visual body
// (row/col item rendering) is regenerated by Excel on open via the cache's
// refreshOnLoad flag, so this need not reproduce every producer's formatting.
// ---------------------------------------------------------------------------

// PivotAxis identifies which pivot axis a field sits on.
type PivotAxis int

const (
	// PivotAxisNone is a field that is not placed on any axis.
	PivotAxisNone PivotAxis = iota
	// PivotAxisRow places the field on the row axis.
	PivotAxisRow
	// PivotAxisCol places the field on the column axis.
	PivotAxisCol
	// PivotAxisPage places the field on the page (report filter) axis.
	PivotAxisPage
)

// CT_PivotField models one pivotField: its axis and, for a row/column field,
// the count of shared items it exposes (so the marshaler can emit the
// <items> list).
type CT_PivotField struct {
	Axis      PivotAxis
	DataField bool
	// ItemCount is the number of shared items in the underlying cache field,
	// listed as <item x="i"/> entries for a row/column field.
	ItemCount int
}

// CT_DataField models one dataField (a value field with an aggregation).
type CT_DataField struct {
	Name string // display name, e.g. "Sum of Sales"
	Fld  int    // cache field index
	// Subtotal is the aggregation function ("sum", "count", "average", "min",
	// "max", ...); "" means the schema default ("sum") and is not emitted.
	Subtotal string
}

// CT_PageField models one pageField (report filter).
type CT_PageField struct {
	Fld int
}

// PivotAxisItem is one entry in the rowItems/colItems body: a rendered row or
// column of the pivot. X holds the member indices (into each axis field's
// <items> list) that changed from the previous entry; R is the count of
// leading members repeated from the previous entry.
type PivotAxisItem struct {
	Type string // "" (data), "grand" (grand total), "default"
	I    int    // data field index (@i); 0 omits the attribute
	R    int    // repeated leading members (@r); 0 omits the attribute
	X    []int  // member indices for this entry, deepest levels
}

// CT_PivotTableDefinition models a pivot table definition part.
type CT_PivotTableDefinition struct {
	Name        string
	CacheId     uint32
	DataCaption string
	LocationRef string

	FirstHeaderRow uint32
	FirstDataRow   uint32
	FirstDataCol   uint32
	RowPageCount   uint32
	ColPageCount   uint32

	PivotFields []CT_PivotField
	RowFields   []int // cache field indices; -2 marks the data-values dimension
	ColFields   []int
	RowItems    []PivotAxisItem
	ColItems    []PivotAxisItem
	PageFields  []CT_PageField
	DataFields  []CT_DataField
}

// --- Read ---

type xmlPivotTableDefinition struct {
	XMLName     xml.Name `xml:"pivotTableDefinition"`
	Name        string   `xml:"name,attr"`
	CacheID     uint32   `xml:"cacheId,attr"`
	DataCaption string   `xml:"dataCaption,attr"`
	Location    struct {
		Ref string `xml:"ref,attr"`
	} `xml:"location"`
	PivotFields struct {
		Field []struct {
			Axis      string `xml:"axis,attr"`
			DataField string `xml:"dataField,attr"`
		} `xml:"pivotField"`
	} `xml:"pivotFields"`
	RowFields struct {
		Field []struct {
			X int `xml:"x,attr"`
		} `xml:"field"`
	} `xml:"rowFields"`
	ColFields struct {
		Field []struct {
			X int `xml:"x,attr"`
		} `xml:"field"`
	} `xml:"colFields"`
	PageFields struct {
		Field []struct {
			Fld int `xml:"fld,attr"`
		} `xml:"pageField"`
	} `xml:"pageFields"`
	DataFields struct {
		Field []struct {
			Name     string `xml:"name,attr"`
			Fld      int    `xml:"fld,attr"`
			Subtotal string `xml:"subtotal,attr"`
		} `xml:"dataField"`
	} `xml:"dataFields"`
}

// ParsePivotTableDefinition decodes a pivot table definition part.
func ParsePivotTableDefinition(data []byte) (*CT_PivotTableDefinition, error) {
	var x xmlPivotTableDefinition
	if err := xml.Unmarshal(data, &x); err != nil {
		return nil, err
	}
	def := &CT_PivotTableDefinition{
		Name:        x.Name,
		CacheId:     x.CacheID,
		DataCaption: x.DataCaption,
		LocationRef: x.Location.Ref,
	}
	for _, f := range x.PivotFields.Field {
		pf := CT_PivotField{DataField: parseOnOff(f.DataField)}
		switch f.Axis {
		case "axisRow":
			pf.Axis = PivotAxisRow
		case "axisCol":
			pf.Axis = PivotAxisCol
		case "axisPage":
			pf.Axis = PivotAxisPage
		}
		def.PivotFields = append(def.PivotFields, pf)
	}
	for _, f := range x.RowFields.Field {
		def.RowFields = append(def.RowFields, f.X)
	}
	for _, f := range x.ColFields.Field {
		def.ColFields = append(def.ColFields, f.X)
	}
	for _, f := range x.PageFields.Field {
		def.PageFields = append(def.PageFields, CT_PageField{Fld: f.Fld})
	}
	for _, f := range x.DataFields.Field {
		def.DataFields = append(def.DataFields, CT_DataField{
			Name:     f.Name,
			Fld:      f.Fld,
			Subtotal: f.Subtotal,
		})
	}
	return def, nil
}

// --- Write ---

// MarshalPivotTableDefinition serializes a pivot table definition part.
func MarshalPivotTableDefinition(def *CT_PivotTableDefinition) []byte {
	b := xmlb.NewBuilder()
	b.RegisterNamespace(nsSpreadsheetML, "")
	b.WriteHeader()

	dataCaption := def.DataCaption
	if dataCaption == "" {
		dataCaption = "Values"
	}
	b.StartElementWithNS(nsSpreadsheetML, "pivotTableDefinition",
		[]xmlb.NSDecl{{Prefix: "", URI: nsSpreadsheetML}},
		xmlb.StrAttr("name", def.Name),
		xmlb.UintAttr("cacheId", def.CacheId),
		xmlb.BoolAttr("applyNumberFormats", false),
		xmlb.BoolAttr("applyBorderFormats", false),
		xmlb.BoolAttr("applyFontFormats", false),
		xmlb.BoolAttr("applyPatternFormats", false),
		xmlb.BoolAttr("applyAlignmentFormats", false),
		xmlb.BoolAttr("applyWidthHeightFormats", true),
		xmlb.StrAttr("dataCaption", dataCaption),
		xmlb.UintAttr("updatedVersion", pivotRefreshVersion),
		xmlb.UintAttr("minRefreshableVersion", pivotMinRefreshables),
		xmlb.BoolAttr("useAutoFormatting", true),
		xmlb.BoolAttr("itemPrintTitles", true),
		xmlb.UintAttr("createdVersion", pivotCreatedVersion),
		xmlb.BoolAttr("indent", false),
		xmlb.BoolAttr("outline", true),
		xmlb.BoolAttr("outlineData", true),
		xmlb.BoolAttr("multipleFieldFilters", false),
	)

	locAttrs := []xmlb.Attr{
		xmlb.StrAttr("ref", def.LocationRef),
		xmlb.UintAttr("firstHeaderRow", def.FirstHeaderRow),
		xmlb.UintAttr("firstDataRow", def.FirstDataRow),
		xmlb.UintAttr("firstDataCol", def.FirstDataCol),
	}
	if def.RowPageCount > 0 {
		locAttrs = append(locAttrs, xmlb.UintAttr("rowPageCount", def.RowPageCount))
	}
	if def.ColPageCount > 0 {
		locAttrs = append(locAttrs, xmlb.UintAttr("colPageCount", def.ColPageCount))
	}
	b.EmptyElement(nsSpreadsheetML, "location", locAttrs...)

	// pivotFields
	b.StartElement(nsSpreadsheetML, "pivotFields",
		xmlb.UintAttr("count", uint32(len(def.PivotFields))))
	for i := range def.PivotFields {
		marshalPivotField(b, &def.PivotFields[i])
	}
	b.EndElement(nsSpreadsheetML, "pivotFields")

	marshalAxisFields(b, "rowFields", def.RowFields)
	marshalAxisItems(b, "rowItems", def.RowItems)
	marshalAxisFields(b, "colFields", def.ColFields)
	marshalAxisItems(b, "colItems", def.ColItems)

	if len(def.PageFields) > 0 {
		b.StartElement(nsSpreadsheetML, "pageFields",
			xmlb.UintAttr("count", uint32(len(def.PageFields))))
		for _, pf := range def.PageFields {
			b.EmptyElement(nsSpreadsheetML, "pageField",
				xmlb.IntAttr("fld", int64(pf.Fld)),
				xmlb.IntAttr("hier", -1))
		}
		b.EndElement(nsSpreadsheetML, "pageFields")
	}

	if len(def.DataFields) > 0 {
		b.StartElement(nsSpreadsheetML, "dataFields",
			xmlb.UintAttr("count", uint32(len(def.DataFields))))
		for _, df := range def.DataFields {
			attrs := []xmlb.Attr{
				xmlb.StrAttr("name", df.Name),
				xmlb.IntAttr("fld", int64(df.Fld)),
			}
			if df.Subtotal != "" && df.Subtotal != "sum" {
				attrs = append(attrs, xmlb.StrAttr("subtotal", df.Subtotal))
			}
			attrs = append(attrs, xmlb.IntAttr("baseField", 0), xmlb.IntAttr("baseItem", 0))
			b.EmptyElement(nsSpreadsheetML, "dataField", attrs...)
		}
		b.EndElement(nsSpreadsheetML, "dataFields")
	}

	b.EmptyElement(nsSpreadsheetML, "pivotTableStyleInfo",
		xmlb.StrAttr("name", "PivotStyleLight16"),
		xmlb.BoolAttr("showRowHeaders", true),
		xmlb.BoolAttr("showColHeaders", true),
		xmlb.BoolAttr("showRowStripes", false),
		xmlb.BoolAttr("showColStripes", false),
		xmlb.BoolAttr("showLastColumn", true))

	b.EndElement(nsSpreadsheetML, "pivotTableDefinition")
	_ = b.Finish()
	return b.Bytes()
}

func marshalPivotField(b *xmlb.Builder, pf *CT_PivotField) {
	attrs := []xmlb.Attr{}
	switch pf.Axis {
	case PivotAxisRow:
		attrs = append(attrs, xmlb.StrAttr("axis", "axisRow"))
	case PivotAxisCol:
		attrs = append(attrs, xmlb.StrAttr("axis", "axisCol"))
	case PivotAxisPage:
		attrs = append(attrs, xmlb.StrAttr("axis", "axisPage"))
	}
	if pf.DataField {
		attrs = append(attrs, xmlb.BoolAttr("dataField", true))
	}
	attrs = append(attrs, xmlb.BoolAttr("showAll", false))

	if pf.Axis == PivotAxisRow || pf.Axis == PivotAxisCol || pf.Axis == PivotAxisPage {
		b.StartElement(nsSpreadsheetML, "pivotField", attrs...)
		b.StartElement(nsSpreadsheetML, "items", xmlb.UintAttr("count", uint32(pf.ItemCount+1)))
		for i := 0; i < pf.ItemCount; i++ {
			b.EmptyElement(nsSpreadsheetML, "item", xmlb.IntAttr("x", int64(i)))
		}
		b.EmptyElement(nsSpreadsheetML, "item", xmlb.StrAttr("t", "default"))
		b.EndElement(nsSpreadsheetML, "items")
		b.EndElement(nsSpreadsheetML, "pivotField")
		return
	}
	b.EmptyElement(nsSpreadsheetML, "pivotField", attrs...)
}

func marshalAxisFields(b *xmlb.Builder, name string, fields []int) {
	if len(fields) == 0 {
		return
	}
	b.StartElement(nsSpreadsheetML, name, xmlb.UintAttr("count", uint32(len(fields))))
	for _, f := range fields {
		b.EmptyElement(nsSpreadsheetML, "field", xmlb.IntAttr("x", int64(f)))
	}
	b.EndElement(nsSpreadsheetML, name)
}

func marshalAxisItems(b *xmlb.Builder, name string, items []PivotAxisItem) {
	if len(items) == 0 {
		return
	}
	b.StartElement(nsSpreadsheetML, name, xmlb.UintAttr("count", uint32(len(items))))
	for _, it := range items {
		iAttrs := []xmlb.Attr{}
		if it.Type != "" {
			iAttrs = append(iAttrs, xmlb.StrAttr("t", it.Type))
		}
		if it.I > 0 {
			iAttrs = append(iAttrs, xmlb.IntAttr("i", int64(it.I)))
		}
		if it.R > 0 {
			iAttrs = append(iAttrs, xmlb.IntAttr("r", int64(it.R)))
		}
		if len(it.X) == 0 {
			b.EmptyElement(nsSpreadsheetML, "i", iAttrs...)
			continue
		}
		b.StartElement(nsSpreadsheetML, "i", iAttrs...)
		for _, x := range it.X {
			if x == 0 {
				b.EmptyElement(nsSpreadsheetML, "x")
			} else {
				b.EmptyElement(nsSpreadsheetML, "x", xmlb.IntAttr("v", int64(x)))
			}
		}
		b.EndElement(nsSpreadsheetML, "i")
	}
	b.EndElement(nsSpreadsheetML, name)
}
