package opc

import (
	"bytes"
	"strings"
	"testing"
)

// --- C393: content types must not be steerable from a foreign namespace ----

// TestContentTypesIgnoresForeignNamespace is the regression test for C393.
// UnmarshalContentTypes dispatched on the local name alone, so an
// <evil:Override> — an element every conformant consumer ignores — set the
// content type that drives every downstream part-kind decision.
func TestContentTypesIgnoresForeignNamespace(t *testing.T) {
	src := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` + "\r\n" +
		`<Types xmlns="` + ContentTypesNamespace + `" xmlns:evil="urn:evil">` +
		`<Default Extension="xml" ContentType="application/xml"/>` +
		`<evil:Override PartName="/word/document.xml" ContentType="application/evil"/>` +
		`<evil:Default Extension="png" ContentType="application/evil"/>` +
		`</Types>`

	ct, err := UnmarshalContentTypes([]byte(src))
	if err != nil {
		t.Fatalf("UnmarshalContentTypes() error = %v", err)
	}
	if got := ct.GetContentType("/word/document.xml"); got == "application/evil" {
		t.Errorf("GetContentType(/word/document.xml) = %q; a foreign-namespace Override must not steer the part kind (C393)", got)
	}
	if got := ct.GetContentType("/word/document.xml"); got != "application/xml" {
		t.Errorf("GetContentType(/word/document.xml) = %q, want the Default mapping %q", got, "application/xml")
	}
	if got := ct.GetContentType("/ppt/media/i.png"); got == "application/evil" {
		t.Errorf("a foreign-namespace Default was honoured: %q", got)
	}
	if _, ok := ct.Overrides["/word/document.xml"]; ok {
		t.Error("a foreign-namespace Override entered Overrides")
	}

	// The foreign markup must survive regeneration rather than be dropped.
	out, err := ct.Marshal()
	if err != nil {
		t.Fatalf("Marshal() error = %v", err)
	}
	if !bytes.Equal(out, []byte(src)) {
		t.Errorf("round-trip is not byte-identical:\n got %s\nwant %s", out, src)
	}
}

// TestContentTypesAcceptsLegacyNamespaceless keeps the tolerance the parser has
// always had: files with no namespace declaration at all still parse. Real
// producers are sloppy and C393 must reject the hostile case only.
func TestContentTypesAcceptsLegacyNamespaceless(t *testing.T) {
	src := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` + "\r\n" +
		`<Types><Default Extension="xml" ContentType="application/xml"/>` +
		`<Override PartName="/word/document.xml" ContentType="` + ContentTypeDocument + `"/></Types>`

	ct, err := UnmarshalContentTypes([]byte(src))
	if err != nil {
		t.Fatalf("UnmarshalContentTypes() error = %v", err)
	}
	if got := ct.GetContentType("/word/document.xml"); got != ContentTypeDocument {
		t.Errorf("GetContentType() = %q, want %q for a namespace-less legacy file", got, ContentTypeDocument)
	}
}

// TestContentTypesPrefixedNamespaceStillHonoured covers the other real-world
// spelling: the content-types namespace bound to an explicit prefix.
func TestContentTypesPrefixedNamespaceStillHonoured(t *testing.T) {
	src := `<?xml version="1.0" encoding="UTF-8"?>` + "\r\n" +
		`<ct:Types xmlns:ct="` + ContentTypesNamespace + `">` +
		`<ct:Override PartName="/word/document.xml" ContentType="` + ContentTypeDocument + `"/></ct:Types>`

	ct, err := UnmarshalContentTypes([]byte(src))
	if err != nil {
		t.Fatalf("UnmarshalContentTypes() error = %v", err)
	}
	if got := ct.GetContentType("/word/document.xml"); got != ContentTypeDocument {
		t.Errorf("GetContentType() = %q, want %q for a prefixed content-types namespace", got, ContentTypeDocument)
	}
}

// --- C449: comments and a non-canonical </Types> must survive --------------

// TestContentTypesPreservesCommentsAndRootEnd is the regression test for C449:
// a comment inside <Types> fell into the token loop's default branch and its
// raw span was discarded, and Marshal hardcoded "</Types>" over a captured
// "</Types >". Both bite on the preserved-then-modified path.
func TestContentTypesPreservesCommentsAndRootEnd(t *testing.T) {
	src := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` + "\r\n" +
		`<Types xmlns="` + ContentTypesNamespace + `">` +
		`<!-- generated by a producer -->` +
		`<Default Extension="xml" ContentType="application/xml"/>` +
		`<!-- overrides follow -->` +
		`<Override PartName="/word/document.xml" ContentType="` + ContentTypeDocument + `"/>` +
		`</Types >`

	ct, err := UnmarshalContentTypes([]byte(src))
	if err != nil {
		t.Fatalf("UnmarshalContentTypes() error = %v", err)
	}
	out, err := ct.Marshal()
	if err != nil {
		t.Fatalf("Marshal() error = %v", err)
	}
	if !bytes.Equal(out, []byte(src)) {
		t.Errorf("regeneration is not byte-identical:\n got %s\nwant %s", out, src)
	}

	// The same file after a modification (the C46 merge path) keeps its
	// comments and its end tag; only the new entry is appended.
	ct.SetOverride("/word/header1.xml", ContentTypeDocHeader)
	out, err = ct.Marshal()
	if err != nil {
		t.Fatalf("Marshal() after modification error = %v", err)
	}
	got := string(out)
	for _, want := range []string{"<!-- generated by a producer -->", "<!-- overrides follow -->", "</Types >"} {
		if !strings.Contains(got, want) {
			t.Errorf("modified regeneration lost %q:\n%s", want, got)
		}
	}
	if !strings.Contains(got, "/word/header1.xml") {
		t.Errorf("modified regeneration lost the new override:\n%s", got)
	}
}

// --- C396: a repeated core.xml element must be emitted once ----------------

// TestCorePropertiesRepeatedElementEmittedOnce is the regression test for
// C396: elementOrder recorded every occurrence and Marshal replayed it with no
// seen-set, so a duplicated dc:title came out twice, both carrying the
// last-parsed value — schema-invalid and a silent rewrite of the first
// element's data.
func TestCorePropertiesRepeatedElementEmittedOnce(t *testing.T) {
	src := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` + "\r\n" +
		`<cp:coreProperties xmlns:cp="` + nsCoreProperties + `" xmlns:dc="` + nsDublinCore + `">` +
		`<dc:title>first</dc:title><dc:title>second</dc:title>` +
		`</cp:coreProperties>`

	cp, err := UnmarshalCoreProperties([]byte(src))
	if err != nil {
		t.Fatalf("UnmarshalCoreProperties() error = %v", err)
	}
	out, err := cp.Marshal()
	if err != nil {
		t.Fatalf("Marshal() error = %v", err)
	}
	if n := strings.Count(string(out), "<dc:title>"); n != 1 {
		t.Errorf("dc:title emitted %d times, want 1 (maxOccurs=1) — output:\n%s", n, out)
	}
}

// --- C451: the root element must actually be the one named in the error ----

// TestUnmarshalCorePropertiesRejectsForeignRoot is the regression test for the
// core.xml half of C451: "<foo><dc:title>x</dc:title></foo>" parsed as core
// properties while the error message claimed a check that did not exist.
func TestUnmarshalCorePropertiesRejectsForeignRoot(t *testing.T) {
	bad := `<?xml version="1.0"?><foo xmlns:dc="` + nsDublinCore + `"><dc:title>x</dc:title></foo>`
	if _, err := UnmarshalCoreProperties([]byte(bad)); err == nil {
		t.Error("UnmarshalCoreProperties() accepted a document whose root is not coreProperties (C451)")
	}

	// Real spellings still parse, including a namespace-less legacy one.
	for _, good := range []string{
		`<?xml version="1.0"?><cp:coreProperties xmlns:cp="` + nsCoreProperties + `" xmlns:dc="` + nsDublinCore + `"><dc:title>x</dc:title></cp:coreProperties>`,
		`<?xml version="1.0"?><coreProperties><title>x</title></coreProperties>`,
	} {
		cp, err := UnmarshalCoreProperties([]byte(good))
		if err != nil {
			t.Errorf("UnmarshalCoreProperties(%s) error = %v", good, err)
			continue
		}
		if cp.Title != "x" {
			t.Errorf("Title = %q, want %q", cp.Title, "x")
		}
	}
}

// TestUnmarshalCustomPropertiesRejectsForeignRoot is the custom.xml half.
func TestUnmarshalCustomPropertiesRejectsForeignRoot(t *testing.T) {
	bad := `<?xml version="1.0"?><foo><property fmtid="` + CustomPropertiesFmtID + `" pid="2" name="k"><vt:lpwstr xmlns:vt="` + nsDocPropsVTypes + `">v</vt:lpwstr></property></foo>`
	if _, err := UnmarshalCustomProperties([]byte(bad)); err == nil {
		t.Error("UnmarshalCustomProperties() accepted a document whose root is not Properties (C451)")
	}

	good := `<?xml version="1.0"?><Properties xmlns="` + nsCustomProperties + `" xmlns:vt="` + nsDocPropsVTypes + `"><property fmtid="` + CustomPropertiesFmtID + `" pid="2" name="k"><vt:lpwstr>v</vt:lpwstr></property></Properties>`
	cp, err := UnmarshalCustomProperties([]byte(good))
	if err != nil {
		t.Fatalf("UnmarshalCustomProperties() error = %v", err)
	}
	if v, ok := cp.Get("k"); !ok || v != "v" {
		t.Errorf("Get(k) = (%v, %v), want (v, true)", v, ok)
	}
}

// --- C454: a preserved child must carry every prefix it uses ---------------

// TestEnsureSelfContainedNSCoversDescendants is the regression test for C454:
// the injection covered only the preserved element's own prefix, so a
// descendant using a prefix declared on the source root regenerated
// undeclared — exactly the ill-formedness the function exists to prevent.
func TestEnsureSelfContainedNSCoversDescendants(t *testing.T) {
	src := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` + "\r\n" +
		`<cp:coreProperties xmlns:cp="` + nsCoreProperties + `" xmlns:dc="` + nsDublinCore + `"` +
		` xmlns:x="urn:x" xmlns:y="urn:y" xmlns:z="urn:z">` +
		`<dc:title>T</dc:title>` +
		`<x:a><y:b z:att="1"/></x:a>` +
		`</cp:coreProperties>`

	cp, err := UnmarshalCoreProperties([]byte(src))
	if err != nil {
		t.Fatalf("UnmarshalCoreProperties() error = %v", err)
	}
	out, err := cp.Marshal()
	if err != nil {
		t.Fatalf("Marshal() error = %v", err)
	}

	// The regenerated part must be namespace-well-formed: re-parsing it
	// resolves every prefix, and an undeclared one is a hard XML error.
	if _, err := UnmarshalCoreProperties(out); err != nil {
		t.Fatalf("regenerated core.xml does not parse: %v\n%s", err, out)
	}
	for _, want := range []string{`xmlns:x="urn:x"`, `xmlns:y="urn:y"`, `xmlns:z="urn:z"`} {
		if !strings.Contains(string(out), want) {
			t.Errorf("regenerated core.xml is missing %s (C454):\n%s", want, out)
		}
	}
	// And no prefix is declared twice on the same element.
	if n := strings.Count(string(out), `xmlns:x="urn:x"`); n != 1 {
		t.Errorf("xmlns:x declared %d times, want 1:\n%s", n, out)
	}
}

// TestEnsureSelfContainedNSDoesNotOverInject keeps byte-identity for the
// common case: a child that declares its own prefix gains nothing.
func TestEnsureSelfContainedNSDoesNotOverInject(t *testing.T) {
	src := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` + "\r\n" +
		`<cp:coreProperties xmlns:cp="` + nsCoreProperties + `" xmlns:dc="` + nsDublinCore + `"` +
		` xmlns:dcterms="` + nsDcTerms + `" xmlns:dcmitype="` + nsDcmiType + `" xmlns:xsi="` + nsXsi + `">` +
		`<dc:title>T</dc:title><x:custom xmlns:x="urn:x" flag="1">v</x:custom>` +
		`</cp:coreProperties>`

	cp, err := UnmarshalCoreProperties([]byte(src))
	if err != nil {
		t.Fatalf("UnmarshalCoreProperties() error = %v", err)
	}
	out, err := cp.Marshal()
	if err != nil {
		t.Fatalf("Marshal() error = %v", err)
	}
	if !bytes.Equal(out, []byte(src)) {
		t.Errorf("round-trip is not byte-identical:\n got %s\nwant %s", out, src)
	}
}

// --- C455: nil-receiver symmetry -------------------------------------------

// TestCustomPropertiesNilReceiver is the regression test for C455: Set and
// Marshal panicked on the nil receiver that Reader.CustomProperties is
// documented to be when a package has none, while eight sibling methods
// nil-guarded.
func TestCustomPropertiesNilReceiver(t *testing.T) {
	var cp *CustomProperties

	err := cp.Set("k", "v")
	if err == nil {
		t.Error("Set on a nil receiver returned no error")
	} else if !strings.Contains(err.Error(), "nil") {
		t.Errorf("Set error = %v, want it to name the nil receiver", err)
	}

	data, err := cp.Marshal()
	if err != nil {
		t.Fatalf("Marshal on a nil receiver error = %v", err)
	}
	got, err := UnmarshalCustomProperties(data)
	if err != nil {
		t.Fatalf("the nil receiver's Marshal output does not parse: %v\n%s", err, data)
	}
	if got.Len() != 0 {
		t.Errorf("nil receiver marshalled %d properties, want 0", got.Len())
	}

	// The documented fix works.
	cp = &CustomProperties{}
	if err := cp.Set("k", "v"); err != nil {
		t.Errorf("Set on a fresh &CustomProperties{} error = %v", err)
	}
}
