package docx

import (
	"github.com/mgilbir/spine/common/dml"
	xmlb "github.com/mgilbir/spine/common/xml"
	"github.com/mgilbir/spine/opc"
)

// Theme returns a read/write handle to the document's theme part
// (word/theme/theme1.xml), the shared DrawingML a:theme model exposed by
// dml.ThemeEditor. Color-scheme and font-scheme edits made through the handle
// are written back to the theme part on save; an untouched theme round-trips
// byte-for-byte from its preserved source bytes.
//
// It returns nil when the document has no theme part — matching pptx's
// behavior for programmatically created files, whose default theme part is not
// modeled.
func (d *Document) Theme() *dml.ThemeEditor {
	if d.themeResolved {
		return d.theme
	}
	d.themeResolved = true

	name, data := d.themePart()
	if data == nil {
		return nil
	}
	var t dml.Theme
	if err := xmlb.Unmarshal(data, &t); err != nil {
		return nil
	}
	d.theme = dml.NewThemeEditor(&t, data)
	d.themePartName = name
	return d.theme
}

// themePart locates the theme part reachable from the main document part's
// relationships and returns its name and preserved bytes, or ("", nil) when
// there is none.
func (d *Document) themePart() (string, []byte) {
	main := d.mainPart()
	for _, rel := range d.relationships[main] {
		if rel.Type != opc.RelTypeTheme {
			continue
		}
		name := opc.ResolvePartName(main, rel.Target)
		if part, ok := d.preservedParts[name]; ok {
			return name, part.Data
		}
	}
	return "", nil
}

// regeneratedThemePart returns the theme part name and its re-serialized bytes
// when the session edited the theme, or ("", nil) otherwise. The round-trip
// save writes the regenerated bytes in place of the preserved source part.
func (d *Document) regeneratedThemePart() (string, []byte) {
	if d.theme == nil || !d.theme.Modified() {
		return "", nil
	}
	data, err := d.theme.Marshal()
	if err != nil {
		return "", nil
	}
	return d.themePartName, data
}
