package docx

import (
	"strings"
	"testing"
)

func TestRootCommentAndTrailingWS(t *testing.T) {
	fixture := fixtureWithDocument(t, fixtureWNS,
		`<!-- Generated by X --><w:body><w:p/></w:body>`+"\r\n")
	out := openSave(t, fixture)
	if !strings.Contains(out, `<!-- Generated by X -->`) {
		t.Errorf("root comment dropped:\n%s", out)
	}
	if !strings.Contains(out, "</w:body>\r\n</w:document>") {
		t.Errorf("trailing whitespace dropped:\n%s", out)
	}
}
