package xlsx

import (
	"github.com/mgilbir/spine/common/dml"
	xmlb "github.com/mgilbir/spine/common/xml"
	"github.com/mgilbir/spine/opc"
)

// Theme returns a read/write handle to the workbook's theme part
// (xl/theme/theme1.xml), the shared DrawingML a:theme model exposed by
// dml.ThemeEditor. Color-scheme and font-scheme edits made through the handle
// are written back to the theme part on save; an untouched theme round-trips
// byte-for-byte from its preserved source bytes.
//
// It returns nil when the workbook has no theme part — matching pptx's
// behavior for programmatically created files, whose default theme part is not
// modeled.
func (w *Workbook) Theme() *dml.ThemeEditor {
	if w.themeResolved {
		return w.theme
	}
	w.themeResolved = true

	name, data := w.themePart()
	if data == nil {
		return nil
	}
	var t dml.Theme
	if err := xmlb.Unmarshal(data, &t); err != nil {
		return nil
	}
	w.theme = dml.NewThemeEditor(&t, data)
	w.themePartName = name
	return w.theme
}

// themePart locates the theme part reachable from the main workbook part's
// relationships and returns its name and preserved bytes, or ("", nil) when
// there is none.
func (w *Workbook) themePart() (string, []byte) {
	main := w.mainPart()
	for _, rel := range w.relationships[main] {
		if rel.Type != opc.RelTypeTheme {
			continue
		}
		name := opc.ResolvePartName(main, rel.Target)
		if part, ok := w.preservedParts[name]; ok {
			return name, part.Data
		}
	}
	return "", nil
}

// regeneratedThemePart returns the theme part name and its re-serialized bytes
// when the session edited the theme, or ("", nil) otherwise. The round-trip
// save writes the regenerated bytes in place of the preserved source part.
func (w *Workbook) regeneratedThemePart() (string, []byte) {
	if w.theme == nil || !w.theme.Modified() {
		return "", nil
	}
	data, err := w.theme.Marshal()
	if err != nil {
		return "", nil
	}
	return w.themePartName, data
}
