package xml

import (
	"bytes"
	"unicode/utf8"
)

// Formatting whitespace and always-regenerated parts.
//
// Some OOXML parts cannot pass through verbatim on save: pptx regenerates
// presentation.xml, every slideLayout and every slideMaster from the parsed
// model because their id lists and rel ids are owned by the package writer.
// Regeneration emits the canonical, unindented form, so a producer that
// pretty-printed those parts loses its indentation on a zero-modification
// round trip — the content is identical, only the inter-element whitespace is
// gone (C587: 13 of 1200 wild decks in the Common Crawl sample).
//
// EqualIgnoringIndent is the predicate that lets those parts fall back to
// their source bytes. It answers exactly one question: "would emitting the
// original bytes instead of these regenerated bytes change what this document
// says?" It compares the two token by token at the *byte* level and forgives
// only the three spellings XML itself defines as interchangeable: whitespace
// between markup in element-only content (§2.10), <x/> against <x></x> (§3.1),
// and a character written literally against the numeric reference that denotes
// it (§4.1). Attribute order, attribute quoting, entity references, element
// order and character data must all match exactly — including whitespace that
// is the entire content of an element, which is character data and not
// indentation.
//
// The alternative — capturing each inter-element gap during unmarshal and
// replaying it during marshal, as xlsx/internal/oxml/workbook.go does for the
// workbook root's children — does not generalize here. pptx layouts and masters
// are the full shape tree: hundreds of pml and dml types marshaled through the
// reflection marshaler, at arbitrary depth. A flat, positionally-indexed gap
// list is the only capture that would not require instrumenting every one of
// them, and it is correct only while the emitted token sequence matches the
// parsed one one-for-one — which is precisely the condition under which the
// source bytes are usable verbatim. Positional replay can also misplace
// whitespace when the sequences drift; falling back to the source cannot.

// EqualIgnoringIndent reports whether a and b are the same XML document except
// for serialization choices XML gives no meaning to:
//
//   - formatting whitespace between markup in element-only content;
//   - whether an empty element is written <x/> or <x></x>;
//   - whether an interchangeable character is written literally or as a
//     numeric character reference (&#149; / &#x95; / U+0095).
//
// Everything else — attribute order, attribute quoting, entity references,
// character data, element order — must match byte for byte.
//
// All three allowances exist for the same reason: wild producers mix the forms
// within a single part (indentation on some elements, <a:pPr algn="ctr"></a:pPr>
// beside <a:noAutofit/>, &#x2022; beside a literal bullet), while regeneration
// applies one canonical choice to every element. None of the three is
// observable once the document is parsed, so preferring the source's spelling
// cannot change what the document says.
//
// It returns false — the safe answer for a caller choosing between two
// serializations — whenever either input is not scannable as well-formed
// markup, so a malformed or truncated part never licenses substituting one for
// the other.
func EqualIgnoringIndent(a, b []byte) bool {
	if bytes.Equal(a, b) {
		return true
	}
	ta, ok := scanRawTokens(a)
	if !ok {
		return false
	}
	tb, ok := scanRawTokens(b)
	if !ok {
		return false
	}
	ia, ib := 0, 0
	for {
		for ia < len(ta) && ignorableIndent(ta, ia) {
			ia++
		}
		for ib < len(tb) && ignorableIndent(tb, ib) {
			ib++
		}
		if ia >= len(ta) || ib >= len(tb) {
			return ia >= len(ta) && ib >= len(tb)
		}
		switch {
		case ta[ia].kind == tb[ib].kind && sameSpelling(ta[ia].raw, tb[ib].raw):
			ia++
			ib++
		case matchEmptyAgainstPair(ta, &ia, tb, &ib):
		case matchEmptyAgainstPair(tb, &ib, ta, &ia):
		default:
			return false
		}
	}
}

// matchEmptyAgainstPair matches a self-closing tag in e at *ei against the
// open/close pair in p at *pi, advancing both cursors when they spell the same
// empty element. The two tags must carry the identical attribute text; only the
// "/" and any whitespace before the closing ">" may differ.
func matchEmptyAgainstPair(e []rawTok, ei *int, p []rawTok, pi *int) bool {
	if e[*ei].kind != rawTokEmpty {
		return false
	}
	if p[*pi].kind != rawTokStart || *pi+1 >= len(p) || p[*pi+1].kind != rawTokEnd {
		return false
	}
	if !bytes.Equal(p[*pi].name, p[*pi+1].name) {
		return false
	}
	if !sameSpelling(tagInner(e[*ei]), tagInner(p[*pi])) {
		return false
	}
	*ei++
	*pi += 2
	return true
}

// tagInner returns a tag's name-and-attributes text: the raw bytes without the
// angle brackets, the self-closing "/", and any whitespace run before ">".
func tagInner(t rawTok) []byte {
	raw := t.raw
	end := len(raw) - 1 // trailing '>'
	if t.kind == rawTokEmpty {
		end-- // trailing '/'
	}
	return bytes.TrimRight(raw[1:end], " \t\r\n")
}

// rawTokKind classifies a token produced by scanRawTokens.
type rawTokKind uint8

const (
	rawTokText   rawTokKind = iota // character data (never entity-decoded)
	rawTokStart                    // <name ...>
	rawTokEnd                      // </name>
	rawTokEmpty                    // <name .../>
	rawTokMarkup                   // <?...?>, <!--...-->, <![CDATA[...]]>, <!...>
)

// rawTok is a verbatim slice of the input plus enough classification to decide
// whether a whitespace run between two tokens is indentation. raw always
// aliases the input; nothing is copied.
type rawTok struct {
	kind rawTokKind
	raw  []byte
	name []byte // element name as written (prefix included), for start/end/empty
}

// scanRawTokens splits an XML document into verbatim tokens. It reports false
// on any construct it cannot terminate (unclosed tag, comment, CDATA or PI),
// which callers treat as "not comparable".
func scanRawTokens(s []byte) ([]rawTok, bool) {
	out := make([]rawTok, 0, 64)
	for i := 0; i < len(s); {
		if s[i] != '<' {
			j := i + 1
			for j < len(s) && s[j] != '<' {
				j++
			}
			out = append(out, rawTok{kind: rawTokText, raw: s[i:j]})
			i = j
			continue
		}
		tok, next, ok := scanMarkupToken(s, i)
		if !ok {
			return nil, false
		}
		out = append(out, tok)
		i = next
	}
	return out, true
}

// delimited scans a construct that runs from s[i:] to the first occurrence of
// closer after the opening delimiter of length openLen.
func delimited(s []byte, i, openLen int, closer string) (rawTok, int, bool) {
	rel := bytes.Index(s[i+openLen:], []byte(closer))
	if rel < 0 {
		return rawTok{}, 0, false
	}
	end := i + openLen + rel + len(closer)
	return rawTok{kind: rawTokMarkup, raw: s[i:end]}, end, true
}

// scanMarkupToken scans the markup construct starting at s[i] (which is '<').
func scanMarkupToken(s []byte, i int) (rawTok, int, bool) {
	rest := s[i:]
	switch {
	case bytes.HasPrefix(rest, []byte("<!--")):
		return delimited(s, i, 4, "-->")
	case bytes.HasPrefix(rest, []byte("<![CDATA[")):
		return delimited(s, i, 9, "]]>")
	case bytes.HasPrefix(rest, []byte("<?")):
		return delimited(s, i, 2, "?>")
	case bytes.HasPrefix(rest, []byte("<!")):
		// DOCTYPE and friends: scan to '>', stepping over an internal subset.
		for j := i + 2; j < len(s); {
			switch s[j] {
			case '[':
				k := bytes.IndexByte(s[j:], ']')
				if k < 0 {
					return rawTok{}, 0, false
				}
				j += k + 1
			case '>':
				return rawTok{kind: rawTokMarkup, raw: s[i : j+1]}, j + 1, true
			default:
				j++
			}
		}
		return rawTok{}, 0, false
	}

	j := i + 1
	isEnd := false
	if j < len(s) && s[j] == '/' {
		isEnd = true
		j++
	}
	nameStart := j
	for j < len(s) && !isTagNameBoundary(s[j]) {
		j++
	}
	name := s[nameStart:j]
	if len(name) == 0 {
		return rawTok{}, 0, false
	}
	var quote byte
	for ; j < len(s); j++ {
		c := s[j]
		if quote != 0 {
			if c == quote {
				quote = 0
			}
			continue
		}
		switch c {
		case '"', '\'':
			quote = c
		case '>':
			kind := rawTokStart
			switch {
			case isEnd:
				kind = rawTokEnd
			case s[j-1] == '/':
				kind = rawTokEmpty
			}
			return rawTok{kind: kind, raw: s[i : j+1], name: name}, j + 1, true
		}
	}
	return rawTok{}, 0, false
}

// isTagNameBoundary reports whether c ends an element name inside a tag.
func isTagNameBoundary(c byte) bool {
	switch c {
	case ' ', '\t', '\r', '\n', '/', '>':
		return true
	}
	return false
}

// ignorableIndent reports whether toks[i] is a whitespace run that only
// formats the markup around it.
//
// A whitespace-only text node is character data — and so significant — when it
// is the entire content of an element: <a:t> </a:t> holds a space, and a
// serialization that dropped it would not be the same document. Every other
// whitespace-only run sits between two pieces of markup in element-only
// content, where XML assigns it no meaning.
func ignorableIndent(toks []rawTok, i int) bool {
	t := toks[i]
	if t.kind != rawTokText || !isAllXMLSpace(t.raw) {
		return false
	}
	if i > 0 && i+1 < len(toks) &&
		toks[i-1].kind == rawTokStart && toks[i+1].kind == rawTokEnd &&
		bytes.Equal(toks[i-1].name, toks[i+1].name) {
		return false
	}
	return true
}

// sameSpelling reports whether two verbatim slices spell the same XML, allowing
// a character to be written either literally or as a numeric character
// reference (&#149; / &#x95; / U+0095 are one and the same character; XML §4.1
// resolves the reference before anything else sees it).
//
// The allowance is restricted to characters that are interchangeable in both
// directions — see interchangeableRune — so an escaping difference that XML
// does treat as meaningful still compares unequal. The '&'-free fast path means
// the vast majority of tokens never allocate.
func sameSpelling(a, b []byte) bool {
	if bytes.Equal(a, b) {
		return true
	}
	if bytes.IndexByte(a, '&') < 0 && bytes.IndexByte(b, '&') < 0 {
		return false
	}
	return bytes.Equal(expandCharRefs(a), expandCharRefs(b))
}

// expandCharRefs replaces every interchangeable numeric character reference in
// s with the character it denotes, leaving everything else — entity references
// included — exactly as written.
func expandCharRefs(s []byte) []byte {
	if bytes.IndexByte(s, '&') < 0 {
		return s
	}
	out := make([]byte, 0, len(s))
	for i := 0; i < len(s); {
		if s[i] != '&' {
			out = append(out, s[i])
			i++
			continue
		}
		r, n, ok := decodeCharRef(s[i:])
		if !ok {
			out = append(out, s[i])
			i++
			continue
		}
		out = utf8.AppendRune(out, r)
		i += n
	}
	return out
}

// decodeCharRef parses a leading "&#DDD;" or "&#xHHH;" and reports the rune it
// denotes together with the length consumed. It reports false for anything it
// does not fully recognize, and for references whose literal spelling is not
// interchangeable with the reference.
func decodeCharRef(s []byte) (rune, int, bool) {
	if len(s) < 4 || s[0] != '&' || s[1] != '#' {
		return 0, 0, false
	}
	i, base := 2, 10
	if s[i] == 'x' || s[i] == 'X' {
		base, i = 16, i+1
	}
	start := i
	var v rune
	for i < len(s) && s[i] != ';' {
		d := hexDigitVal(s[i])
		if d < 0 || d >= base {
			return 0, 0, false
		}
		v = v*rune(base) + rune(d)
		if v > utf8.MaxRune {
			return 0, 0, false
		}
		i++
	}
	if i == start || i >= len(s) {
		return 0, 0, false
	}
	if !interchangeableRune(v) {
		return 0, 0, false
	}
	return v, i + 1, true
}

// hexDigitVal returns the value of an ASCII hex digit, or -1.
func hexDigitVal(c byte) int {
	switch {
	case c >= '0' && c <= '9':
		return int(c - '0')
	case c >= 'a' && c <= 'f':
		return int(c-'a') + 10
	case c >= 'A' && c <= 'F':
		return int(c-'A') + 10
	}
	return -1
}

// interchangeableRune reports whether writing r literally and writing it as a
// numeric character reference produce the same document.
//
// They do not for the markup delimiters (a literal '<' or '&' is not even
// well-formed where the reference is legal, and '>', '"' and '\” are
// conditionally significant), nor for tab, newline and carriage return: XML
// §3.3.3 normalizes those to a space inside an attribute value when written
// literally but keeps them verbatim when written as a reference, and §2.11
// normalizes literal line endings in content. Characters outside the XML §2.2
// Char production cannot appear literally at all.
func interchangeableRune(r rune) bool {
	switch r {
	case '<', '>', '&', '"', '\'', 0x09, 0x0A, 0x0D:
		return false
	}
	switch {
	case r < 0x20:
		return false
	case r >= 0xD800 && r <= 0xDFFF:
		return false
	case r == 0xFFFE || r == 0xFFFF:
		return false
	case r > utf8.MaxRune:
		return false
	}
	return true
}

// isAllXMLSpace reports whether b consists entirely of XML whitespace (§2.3
// S production). An empty run counts as whitespace.
func isAllXMLSpace(b []byte) bool {
	for _, c := range b {
		switch c {
		case ' ', '\t', '\r', '\n':
		default:
			return false
		}
	}
	return true
}
