package ciguard_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// Every package with a fuzz target has a slot in the nightly matrix.
//
// The nightly used to walk all sixty targets in one job, so a new package was
// picked up automatically. It now runs a job per package, which is what gives
// each target minutes instead of seconds — and which makes the package list a
// thing that can fall behind the code. It already had: common/dml carried
// targets that no matrix entry named, and the matrix named common/xml, which
// carries none. Neither is visible in a green run: the job simply fuzzes
// nothing, or fuzzes a package that is not there.
//
// So the list is checked against the source rather than trusted. A regex over
// the workflow is enough — the file is generated by nobody and the shape is two
// fixed keys — and the alternative is a YAML dependency for one assertion.
func TestFuzzMatrixCoversEveryFuzzedPackage(t *testing.T) {
	root := repoRoot(t)

	inMatrix := matrixPackages(t, filepath.Join(root, ".github/workflows/scheduled.yml"))
	if len(inMatrix) == 0 {
		t.Fatal("no packages parsed out of the fuzz matrix; the parse is broken, not the workflow")
	}
	withTargets := packagesWithFuzzTargets(t, root)
	if len(withTargets) == 0 {
		t.Fatal("no packages with fuzz targets found; the search is broken, not the tree")
	}

	for _, pkg := range withTargets {
		if !inMatrix[pkg] {
			t.Errorf("package %s has fuzz targets and no entry in the nightly matrix, so nothing fuzzes it", pkg)
		}
	}
	for pkg := range inMatrix {
		if !contains(withTargets, pkg) {
			t.Errorf("the nightly matrix names %s, which has no fuzz targets; the job spends its slot on nothing", pkg)
		}
	}
}

// matrixPackages reads the pkg entries out of the fuzz job's matrix.
func matrixPackages(t *testing.T, workflow string) map[string]bool {
	t.Helper()
	data, err := os.ReadFile(workflow)
	if err != nil {
		t.Fatalf("reading %s: %v", workflow, err)
	}
	out := map[string]bool{}
	for _, m := range regexp.MustCompile(`(?m)^\s*- pkg:\s*(\S+)\s*$`).FindAllStringSubmatch(string(data), -1) {
		out[m[1]] = true
	}
	return out
}

// packagesWithFuzzTargets lists the packages declaring a fuzz target, the same
// way the Makefile's sweep discovers them.
func packagesWithFuzzTargets(t *testing.T, root string) []string {
	t.Helper()
	cmd := exec.Command("git", "grep", "-l", "^func Fuzz", "--", "*_test.go")
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		t.Skipf("git grep unavailable: %v", err)
	}
	seen := map[string]bool{}
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if line == "" {
			continue
		}
		seen[filepath.Dir(line)] = true
	}
	pkgs := make([]string, 0, len(seen))
	for p := range seen {
		pkgs = append(pkgs, p)
	}
	sort.Strings(pkgs)
	return pkgs
}

func contains(list []string, want string) bool {
	for _, s := range list {
		if s == want {
			return true
		}
	}
	return false
}

func repoRoot(t *testing.T) string {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	return filepath.Dir(filepath.Dir(wd))
}
