// Example: Create a formatted Word document
//
// This example demonstrates page setup, headers/footers, paragraph
// spacing, bullet and numbered lists, formatted tables, and inline
// images using the spine DOCX library.
//
// Run with: go run ./examples/create_document
package main

import (
	"bytes"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"log"
	"os"
	"path/filepath"

	"github.com/mgilbir/spine/docx"
	"github.com/mgilbir/spine/opc"
)

func main() {
	doc := docx.Create()

	doc.Properties.Title = "Spine Demo Document"
	doc.Properties.Creator = "Spine Library"
	doc.Properties.Subject = "Demonstration of the spine DOCX library"

	// ── Page Setup ───────────────────────────────────────────────────

	sec := doc.DefaultSection()
	sec.SetPageSize(docx.PageSizeA4())
	sec.SetMargins(docx.PageMargins{
		Top: 72, Bottom: 72, Left: 72, Right: 72, // 1 inch each
		Header: 36, Footer: 36,
	})

	// ── Header & Footer ──────────────────────────────────────────────

	hdr := doc.AddHeader(docx.HeaderDefault)
	hp := hdr.AddParagraphWithText("Spine Demo Document")
	hp.SetAlignment(docx.AlignmentRight)
	hpRun := hp.Runs()[0]
	hpRun.SetColor("999999")
	hpRun.SetFontSize(9)

	ftr := doc.AddFooter(docx.FooterDefault)
	fp := ftr.AddParagraphWithText("Generated by Spine Library")
	fp.SetAlignment(docx.AlignmentCenter)
	fpRun := fp.Runs()[0]
	fpRun.SetColor("999999")
	fpRun.SetFontSize(9)

	// ── Title ────────────────────────────────────────────────────────

	title := doc.AddHeading("Welcome to Spine", 1)
	title.SetSpaceAfter(12)

	// ── Introduction ─────────────────────────────────────────────────

	intro := doc.AddParagraphWithText(
		"Spine is a Go library for reading and writing Microsoft Office documents. " +
			"It supports PowerPoint (.pptx), Word (.docx), and Excel (.xlsx) formats " +
			"with full round-trip preservation of existing content.")
	intro.SetLineSpacing(1.15)
	intro.SetSpaceAfter(6)
	intro.SetIndentFirstLine(36) // half-inch first line indent

	body2 := doc.AddParagraphWithText(
		"This document was created entirely in Go code, demonstrating paragraph " +
			"formatting, lists, tables, images, headers, and footers.")
	body2.SetLineSpacing(1.15)
	body2.SetSpaceAfter(6)
	body2.SetIndentFirstLine(36)

	// ── Features (Bullet List) ───────────────────────────────────────

	featuresHeading := doc.AddHeading("Features", 2)
	featuresHeading.SetSpaceAfter(6)
	featuresHeading.SetKeepWithNext(true)

	bullets := doc.AddBulletList()
	features := []string{
		"Create Word, Excel, and PowerPoint documents programmatically",
		"Read and modify existing Office files with byte-identical round-trip",
		"Rich paragraph formatting: spacing, indentation, alignment",
		"Tables with borders, shading, and cell formatting",
		"Inline images from files or byte slices",
		"Headers and footers with multiple types (default, first page, even)",
		"Pure Go implementation with no external dependencies",
	}
	for _, feature := range features {
		li := doc.AddParagraphWithText(feature)
		li.SetListStyle(bullets, 0)
		li.SetSpaceAfter(2)
	}

	// ── Getting Started (Numbered List) ──────────────────────────────

	stepsHeading := doc.AddHeading("Getting Started", 2)
	stepsHeading.SetSpaceBefore(12)
	stepsHeading.SetSpaceAfter(6)
	stepsHeading.SetKeepWithNext(true)

	numbered := doc.AddNumberedList()
	steps := []string{
		"Install: go get github.com/mgilbir/spine",
		"Import the package for your document type (docx, xlsx, or pptx)",
		"Create a new document with Create() or open an existing one with Open()",
		"Add content using the fluent API",
		"Save to a file with Save()",
	}
	for _, step := range steps {
		li := doc.AddParagraphWithText(step)
		li.SetListStyle(numbered, 0)
		li.SetSpaceAfter(2)
	}

	// ── Comparison Table ─────────────────────────────────────────────

	tableHeading := doc.AddHeading("Format Comparison", 2)
	tableHeading.SetSpaceBefore(12)
	tableHeading.SetSpaceAfter(6)
	tableHeading.SetKeepWithNext(true)

	tbl := doc.AddTable(4, 3)
	tbl.SetWidth(450) // points
	tbl.SetBorders(docx.TableBorders{
		Top:     &docx.Border{Style: "single", Width: 1, Color: "4472C4"},
		Bottom:  &docx.Border{Style: "single", Width: 1, Color: "4472C4"},
		Left:    &docx.Border{Style: "single", Width: 0.5, Color: "BFBFBF"},
		Right:   &docx.Border{Style: "single", Width: 0.5, Color: "BFBFBF"},
		InsideH: &docx.Border{Style: "single", Width: 0.5, Color: "D9D9D9"},
		InsideV: &docx.Border{Style: "single", Width: 0.5, Color: "D9D9D9"},
	})
	tbl.SetCellMargins(4, 8, 4, 8)

	// Header row
	headerRow := tbl.Rows()[0]
	headerRow.SetHeaderRow(true)
	headerRow.SetHeight(24)
	headerData := []string{"Format", "Extension", "Status"}
	for i, text := range headerData {
		cell := headerRow.Cells()[i]
		cell.SetShading("4472C4")
		cell.SetVerticalAlignment("center")
		p := cell.Paragraphs()[0]
		p.SetAlignment(docx.AlignmentCenter)
		r := p.AddRun()
		r.SetText(text)
		r.SetBold(true)
		r.SetColor("FFFFFF")
	}

	// Data rows
	tableData := [][]string{
		{"PowerPoint", ".pptx", "Full support"},
		{"Word", ".docx", "Full support"},
		{"Excel", ".xlsx", "Full support"},
	}
	for i, rowData := range tableData {
		row := tbl.Rows()[i+1]
		for j, text := range rowData {
			cell := row.Cells()[j]
			cell.SetVerticalAlignment("center")
			if j == 1 {
				// Center-align the extension column
				p := cell.Paragraphs()[0]
				p.SetAlignment(docx.AlignmentCenter)
				r := p.AddRun()
				r.SetText(text)
				r.SetFont("Consolas")
			} else {
				cell.Paragraphs()[0].SetText(text)
			}
		}
		// Alternate row shading
		if i%2 == 0 {
			for j := 0; j < 3; j++ {
				row.Cells()[j].SetShading("F2F7FB")
			}
		}
	}

	// ── Inline Image ─────────────────────────────────────────────────

	imageHeading := doc.AddHeading("Image Support", 2)
	imageHeading.SetSpaceBefore(12)
	imageHeading.SetSpaceAfter(6)

	imgIntro := doc.AddParagraphWithText(
		"Spine supports inline images from files or byte slices. " +
			"Below is a 64x64 blue square generated in memory:")
	imgIntro.SetLineSpacing(1.15)
	imgIntro.SetSpaceAfter(6)

	imgPara := doc.AddParagraph()
	imgPara.SetAlignment(docx.AlignmentCenter)
	imgRun := imgPara.AddRun()
	img, err := imgRun.AddImageFromBytes(blueSquarePNG(64), opc.ContentTypePNG)
	if err != nil {
		log.Fatalf("Failed to add image: %v", err)
	}
	img.SetSize(72, 72) // 1 inch square
	img.SetAltText("Blue square generated by Spine")

	// ── Closing ──────────────────────────────────────────────────────

	closing := doc.AddParagraphWithText(
		"For more information, visit the project repository.")
	closing.SetSpaceBefore(12)
	closing.SetLineSpacing(1.15)

	// ── Save ─────────────────────────────────────────────────────────

	outputPath := "output.docx"
	if len(os.Args) > 1 {
		outputPath = os.Args[1]
	}
	dir := filepath.Dir(outputPath)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			log.Fatalf("Failed to create directory: %v", err)
		}
	}

	if err := doc.Save(outputPath); err != nil {
		log.Fatalf("Failed to save document: %v", err)
	}

	fmt.Printf("Document saved to: %s\n", outputPath)
	fmt.Printf("Paragraphs: %d\n", len(doc.Paragraphs()))
}

// blueSquarePNG generates a solid blue square PNG image of the given size.
func blueSquarePNG(size int) []byte {
	img := image.NewRGBA(image.Rect(0, 0, size, size))
	blue := color.RGBA{R: 68, G: 114, B: 196, A: 255}
	for y := 0; y < size; y++ {
		for x := 0; x < size; x++ {
			img.Set(x, y, blue)
		}
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		log.Fatalf("Failed to encode PNG: %v", err)
	}
	return buf.Bytes()
}
