package pptx

import (
	"strconv"

	"github.com/mgilbir/spine/pptx/internal/oxml"
)

// mediaTimingRef identifies an auto-play media shape by its shape id and kind.
type mediaTimingRef struct {
	spid uint32
	kind mediaKind
}

// applyMediaTiming installs or regenerates the auto-play timing tree for media
// added to the slide. A timing tree parsed from an opened file is never touched
// (rebuilding it would clobber existing animations; such media still plays on
// click). A tree this library generated is regenerated whenever a full shape
// rebuild renumbered the shape ids (the old tree would target nonexistent
// spids) or when more auto-play media was added after it was built.
func (s *Slide) applyMediaTiming() {
	refs := s.autoplayMedia
	s.autoplayMedia = nil
	regen := s.timingRegen
	s.timingRegen = false
	if s.slideXML == nil {
		return
	}
	if s.slideXML.Timing != nil && !s.timingAutoGenerated {
		// Parsed (or otherwise foreign) timing tree: leave it alone.
		return
	}

	if regen {
		// A full rebuild re-collected every auto-play ref with its new shape
		// id; refs is the complete set. Rebuild the generated tree from it, or
		// drop the tree when no auto-play media remains.
		s.autoTimingRefs = refs
		if len(refs) == 0 {
			if s.timingAutoGenerated {
				s.slideXML.Timing = nil
				s.timingAutoGenerated = false
			}
			return
		}
	} else {
		// Append-only sync: refs holds just the media added since the last
		// build (with stable ids); merge into the set the tree covers.
		if len(refs) == 0 {
			return
		}
		s.autoTimingRefs = append(s.autoTimingRefs, refs...)
	}

	s.slideXML.Timing = buildAutoplayTiming(s.autoTimingRefs)
	s.timingAutoGenerated = true
}

// pruneAutoTiming drops the auto-play refs of removed shapes and rebuilds (or
// drops) the generated timing tree so it never targets a deleted spid. Refs
// collected but not yet built into a tree (media added and removed within one
// cycle) are pruned too. A timing tree parsed from an opened file is never
// touched.
func (s *Slide) pruneAutoTiming(spids []uint32) {
	if len(spids) == 0 {
		return
	}
	removed := make(map[uint32]bool, len(spids))
	for _, id := range spids {
		removed[id] = true
	}
	if len(s.autoplayMedia) > 0 {
		kept := s.autoplayMedia[:0]
		for _, ref := range s.autoplayMedia {
			if !removed[ref.spid] {
				kept = append(kept, ref)
			}
		}
		s.autoplayMedia = kept
	}
	if len(s.autoTimingRefs) == 0 {
		return
	}
	kept := s.autoTimingRefs[:0]
	changed := false
	for _, ref := range s.autoTimingRefs {
		if removed[ref.spid] {
			changed = true
			continue
		}
		kept = append(kept, ref)
	}
	if !changed {
		return
	}
	s.autoTimingRefs = kept
	s.rebuildAutoTiming()
}

// syncPlayMode reconciles the auto-play bookkeeping with a play-mode change
// made after the shape was synced. Switching to PlayAutomatically registers
// the shape as pending auto-play media (applyMediaTiming merges it into the
// generated tree at save) — but, like the initial embed, never touches a
// timing tree parsed from a file. Switching to PlayOnClick drops the shape's
// ref and rebuilds (or drops) the generated tree.
func (s *Slide) syncPlayMode(spid uint32, kind mediaKind, mode PlayMode) {
	if spid == 0 || s.slideXML == nil {
		return
	}
	builtIdx := -1
	for i, ref := range s.autoTimingRefs {
		if ref.spid == spid {
			builtIdx = i
			break
		}
	}
	pendingIdx := -1
	for i, ref := range s.autoplayMedia {
		if ref.spid == spid {
			pendingIdx = i
			break
		}
	}

	if mode == PlayAutomatically {
		if builtIdx >= 0 || pendingIdx >= 0 {
			return
		}
		if s.slideXML.Timing != nil && !s.timingAutoGenerated {
			return // parsed timing tree: leave it alone
		}
		s.autoplayMedia = append(s.autoplayMedia, mediaTimingRef{spid: spid, kind: kind})
		return
	}

	// PlayOnClick: forget the shape.
	if pendingIdx >= 0 {
		s.autoplayMedia = append(s.autoplayMedia[:pendingIdx], s.autoplayMedia[pendingIdx+1:]...)
	}
	if builtIdx >= 0 {
		s.autoTimingRefs = append(s.autoTimingRefs[:builtIdx], s.autoTimingRefs[builtIdx+1:]...)
		s.rebuildAutoTiming()
	}
}

// rebuildAutoTiming regenerates the auto-generated timing tree from the
// current ref set, dropping the tree when no auto-play media remains. Trees
// parsed from a file are never touched.
func (s *Slide) rebuildAutoTiming() {
	if s.slideXML == nil || !s.timingAutoGenerated {
		return
	}
	if len(s.autoTimingRefs) == 0 {
		s.slideXML.Timing = nil
		s.timingAutoGenerated = false
		return
	}
	s.slideXML.Timing = buildAutoplayTiming(s.autoTimingRefs)
}

func i32p(v int32) *int32 { return &v }

func spTgt(spid uint32) *oxml.TargetElement {
	return &oxml.TargetElement{SpTgt: &oxml.ShapeTarget{SpId: strconv.FormatUint(uint64(spid), 10)}}
}

func sldTgt() *oxml.TargetElement {
	return &oxml.TargetElement{SldTgt: &oxml.SlideTarget{}}
}

func condDelay(delay string) *oxml.ConditionList {
	return &oxml.ConditionList{Cond: []*oxml.Condition{{Delay: delay}}}
}

func slideEventCond(evt string) *oxml.ConditionList {
	return &oxml.ConditionList{Cond: []*oxml.Condition{{Evt: evt, Delay: "0", TgtEl: sldTgt()}}}
}

// buildAutoplayTiming builds a p:timing tree that auto-plays the given media
// when the slide appears. The structure mirrors what PowerPoint emits for media
// set to "Start: Automatically": a main sequence whose mediacall command issues
// playFrom(0.0) against each media shape, plus a p:video/p:audio media node per
// shape. Time-node ids are independent of shape ids.
func buildAutoplayTiming(refs []mediaTimingRef) *oxml.Timing {
	var next uint32
	id := func() uint32 { next++; return next }

	rootID := id()     // tmRoot
	mainSeqID := id()  // mainSeq
	clickParID := id() // click group (waits: delay indefinite)
	withParID := id()  // with-previous group (delay 0)

	// One mediacall effect per media, nested under the with-previous group.
	effChild := &oxml.TimeNodeList{}
	for i, ref := range refs {
		nodeType := "withEffect"
		if i == 0 {
			nodeType = "afterEffect"
		}
		effID := id()
		bhvrID := id()

		cmdChild := &oxml.TimeNodeList{}
		cmdChild.AppendCmd(&oxml.Command{
			Type: "call",
			Cmd:  "playFrom(0.0)",
			CBhvr: &oxml.CommonBehavior{
				CTn:   &oxml.CommonTimeNode{Id: bhvrID, Fill: "hold"},
				TgtEl: spTgt(ref.spid),
			},
		})
		effChild.AppendPar(&oxml.ParallelTimeNode{CTn: &oxml.CommonTimeNode{
			Id:            effID,
			PresetClass:   "mediacall",
			PresetSubtype: i32p(0),
			Fill:          "hold",
			NodeType:      nodeType,
			StCondLst:     condDelay("0"),
			ChildTnLst:    cmdChild,
		}})
	}

	withChild := &oxml.TimeNodeList{}
	withChild.AppendPar(&oxml.ParallelTimeNode{CTn: &oxml.CommonTimeNode{
		Id: withParID, Fill: "hold", StCondLst: condDelay("0"), ChildTnLst: effChild,
	}})

	// The outer group starts at delay 0 (not the "indefinite" used for
	// click-triggered effects) so the whole play chain fires when the slide's
	// timeline begins — i.e. when the slide appears — rather than on the next
	// advance click.
	clickChild := &oxml.TimeNodeList{}
	clickChild.AppendPar(&oxml.ParallelTimeNode{CTn: &oxml.CommonTimeNode{
		Id: clickParID, Fill: "hold", StCondLst: condDelay("0"), ChildTnLst: withChild,
	}})

	seq := &oxml.SequenceTimeNode{
		Concurrent:  true,
		NextAc:      "seek",
		CTn:         &oxml.CommonTimeNode{Id: mainSeqID, Dur: "indefinite", NodeType: "mainSeq", ChildTnLst: clickChild},
		PrevCondLst: slideEventCond("onPrev"),
		NextCondLst: slideEventCond("onNext"),
	}

	// tmRoot children: the main sequence followed by a media node per shape.
	rootChild := &oxml.TimeNodeList{}
	rootChild.AppendSeq(seq)
	for _, ref := range refs {
		cmn := &oxml.CommonMediaNode{
			CTn:   &oxml.CommonTimeNode{Id: id(), Fill: "hold", StCondLst: condDelay("indefinite")},
			TgtEl: spTgt(ref.spid),
		}
		if ref.kind == mediaAudio {
			rootChild.AppendAudio(&oxml.Audio{CMediaNode: cmn})
		} else {
			rootChild.AppendVideo(&oxml.Video{CMediaNode: cmn})
		}
	}

	tnLst := &oxml.TimeNodeList{}
	tnLst.AppendPar(&oxml.ParallelTimeNode{CTn: &oxml.CommonTimeNode{
		Id: rootID, Dur: "indefinite", Restart: "never", NodeType: "tmRoot", ChildTnLst: rootChild,
	}})

	return &oxml.Timing{TnLst: tnLst}
}
