package pptx

import (
	"encoding/xml"
	"fmt"

	"github.com/mgilbir/spine/common/dml"
	xmlb "github.com/mgilbir/spine/common/xml"
	"github.com/mgilbir/spine/pptx/internal/oxml"
)

// Slide represents a slide in a presentation.
type Slide struct {
	presentation *Presentation
	layout       *SlideLayout
	partName     string
	// sxModel is the parsed slide part. For a slide loaded from a file it is
	// parsed lazily on first access (see sx): a slide round-tripped without
	// inspecting or editing it is never parsed, so the save writes the slide's
	// original bytes verbatim rather than building (and holding) a full model.
	// Reach it through sx(); the save path, sx() itself, validation, and slide
	// construction read/set sxModel + sxParsed directly so they do not trigger a
	// parse.
	sxModel *oxml.Slide
	// sxParsed records that the slide was materialized (parsed on access, or
	// built for a created slide). When sxModel is still nil at save time the
	// slide was never touched, so its original bytes pass through unchanged.
	sxParsed bool
	// sxParseErr holds the failure of a lazy re-parse of bytes loadSlides
	// already parsed — an impossible state that sx() reports by panicking
	// rather than by silently reading the slide as empty (C568).
	sxParseErr error
	index      int
	id         uint32
	relID      string
	// idExtLst preserves the extLst child of this slide's p:sldId entry in
	// presentation.xml, which is regenerated on every save (C225).
	idExtLst *oxml.ExtensionList
	// shapeCache holds the materialized Go-level shapes. It is populated lazily
	// by sx(); read it through shapeList() (which triggers the parse), and let
	// the internal sync machinery read/write it directly.
	shapeCache     []Shape
	shapesModified bool // true if shapes changed via Go API

	// syncedShapes counts the leading shapes already represented in sxModel
	// (the parsed shapes of a loaded slide). When only appends happened,
	// marshal() syncs just the new shapes into the parsed tree instead of
	// rebuilding it — a rebuild drops slide content the domain model cannot
	// represent (group shapes, connectors) and re-numbers every shape.
	syncedShapes int
	// forceShapeRebuild is set by structural edits the surgical/append sync
	// cannot express, forcing a full rebuild from the domain model.
	forceShapeRebuild bool
	// shapeRefs records, for each materialized (parsed) shape in shapes, the
	// child reference in the parsed shape tree it came from. It stays aligned
	// with shapes[:syncedShapes] so a removed shape can be deleted surgically.
	shapeRefs []oxml.ChildRef
	// removedRefs collects the parsed child references removed via RemoveShape,
	// applied at sync time by deleting just those nodes (preserving everything
	// else, including content the domain model cannot represent).
	removedRefs []oxml.ChildRef
	// autoplayMedia records the shape ids of auto-play video/audio added to the
	// slide, collected during the shape sync and used to build the timing tree.
	autoplayMedia []mediaTimingRef
	// autoTimingRefs is the full set of auto-play refs the current generated
	// timing tree was built from. Appends accumulate into it; a full rebuild
	// (which renumbers shape ids) resets it so the tree is regenerated from
	// the fresh ids.
	autoTimingRefs []mediaTimingRef
	// timingAutoGenerated marks the slide's timing tree as one this library
	// built for auto-play media. Only such trees may be regenerated; a timing
	// tree parsed from an opened file is never touched.
	timingAutoGenerated bool
	// timingRegen is set by a full shape rebuild: ids were renumbered and
	// autoplayMedia re-collected from scratch, so any generated timing tree
	// must be rebuilt (or dropped) from that complete set.
	timingRegen bool
	// pendingAnims holds animations added via AddAnimation that have not yet
	// been serialized into the timing tree; applyAnimations flushes them at
	// save. A slide with no pending animations never has its timing touched.
	pendingAnims []*Animation
}

// sx returns the parsed slide model, parsing it lazily from the slide part's
// original bytes on first access and materializing its Go-level shapes. A slide
// that is round-tripped without ever being accessed keeps sxModel nil, so on
// save its original bytes pass through verbatim. Open already validated the
// part (parse-then-discard), so a lazy parse here does not re-surface the
// malformed-slide error Open reports. Parsing never marks the slide modified,
// so an accessed-but-unedited slide still regenerates byte-identically. Returns
// nil only when the bytes are unavailable (a hand-built slide).
//
// If the bytes ARE present and the re-parse fails, that is in-memory corruption
// of bytes loadSlides already parsed successfully, and it panics with a
// diagnostic rather than returning nil. A nil model here reads as an empty
// slide: every shape gone, silently. docx's doc() has always made this choice
// for the identical state (C568); the three copies of this function now agree.
func (s *Slide) sx() *oxml.Slide {
	if s.sxModel == nil && !s.sxParsed {
		s.sxParsed = true
		raw := s.rawBytes()
		if raw == nil {
			return nil
		}
		m := &oxml.Slide{}
		m.Prolog = xmlb.CaptureProlog(raw)
		m.SelfClosingSpace = xmlb.DetectSelfClosingSpace(raw)
		m.CollapseEmpty = xmlb.DetectCollapsedEmptyElements(raw)
		if err := xmlb.UnmarshalWithSource(raw, m); err != nil {
			s.sxParseErr = err
		} else {
			s.sxModel = m
			s.materializeShapes()
		}
	}
	if s.sxParseErr != nil {
		panic(fmt.Sprintf("pptx: lazy parse of slide part %s failed: %v "+
			"(Open validated the same bytes, so this indicates in-memory corruption)",
			s.partName, s.sxParseErr))
	}
	return s.sxModel
}

// rawBytes returns the slide part's original bytes from the presentation's
// still-open reader, or nil when the slide was not loaded from a package (a
// created slide) or its part is unavailable. It is the source for both the lazy
// parse (sx) and the save-time passthrough of an unmodified slide.
func (s *Slide) rawBytes() []byte {
	if s.presentation == nil || s.presentation.reader == nil {
		return nil
	}
	f := s.presentation.reader.GetFile(s.partName)
	if f == nil {
		return nil
	}
	raw, err := f.ReadAll()
	if err != nil {
		return nil
	}
	return raw
}

// ensureModel returns the slide model for a mutator that is about to edit it
// directly, materializing an existing slide's parsed content first (so the edit
// preserves it) and allocating an empty model only when the slide has no bytes
// to parse. Mutators call this before editing so a never-parsed slide is not
// silently replaced with an empty one.
//
// It also records the edit. Such mutators (SetTransition, the background
// setters, SetName) need no flag to persist — materializing the model is itself
// what makes the save regenerate the part — so nothing else notes that the
// slide changed, and the modification timestamp would miss it. Read paths must
// use sx()/materialize() instead; ensureModel means "I am about to write".
func (s *Slide) ensureModel() *oxml.Slide {
	s.presentation.markModelEdited()
	return s.materialize()
}

// materialize returns the slide model, parsing it if needed and allocating an
// empty one for a slide with no bytes, without recording an edit. It is
// ensureModel without the write intent, for the save path (which must be able to
// marshal a slide nobody touched).
func (s *Slide) materialize() *oxml.Slide {
	if s.sx() == nil {
		s.sxModel = newSlideXML()
		s.sxParsed = true
	}
	return s.sxModel
}

// shapeList returns the slide's materialized shapes for read access, triggering
// the lazy parse (see sx) so a never-accessed slide reports its real shapes.
func (s *Slide) shapeList() []Shape {
	s.sx()
	return s.shapeCache
}

// Index returns the 0-based index of the slide in the presentation.
func (s *Slide) Index() int {
	return s.index
}

// RelID returns the slide's presentation-level relationship id (the r:id of its
// p:sldId entry in presentation.xml). For a slide loaded from a file this is its
// stored id; a slide created through this package is assigned a provisional id
// when it is added (not the empty string), which the deck's first save may
// reassign by slide order. It is the identifier a custom show references (see
// Presentation.AddCustomShow) — a reference recorded before save is remapped
// through that reassignment, so it keeps resolving to the same slide.
func (s *Slide) RelID() string {
	return s.relID
}

// Name returns the name of the slide, if any.
func (s *Slide) Name() string {
	if m := s.sx(); m != nil && m.CSld != nil {
		return m.CSld.Name
	}
	return ""
}

// SetName sets the name of the slide.
func (s *Slide) SetName(name string) {
	m := s.ensureModel()
	if m.CSld == nil {
		m.CSld = &oxml.CommonSlideData{}
	}
	m.CSld.Name = name
	s.shapesModified = true
}

// Layout returns the slide layout, or nil if none is set.
func (s *Slide) Layout() *SlideLayout {
	return s.layout
}

// Shapes returns all shapes on the slide.
func (s *Slide) Shapes() []Shape {
	return s.shapeList()
}

// AddShape adds a shape to the slide. It returns an error for shape types the
// library cannot serialize (previously such shapes were accepted and then
// silently dropped on save).
//
// The accepted types are TextBox, PlaceholderShape, AutoShape, Table, Picture,
// Video, Audio, GroupShape and Connector.
//
// ChartFrame, SmartArtFrame and OLEObjectFrame are rejected: they own parts and
// relationships as well as a shape-tree node, so they are created through
// AddChart, AddSmartArt and AddOLEObject rather than assembled and handed over.
// RemoveShape does accept them, so a frame removed by mistake cannot be re-added
// as the same object — recreate it through its Add* constructor.
func (s *Slide) AddShape(shape Shape) error {
	switch shape.(type) {
	case *TextBox, *PlaceholderShape, *AutoShape, *Table, *Picture, *Video, *Audio, *GroupShape, *Connector:
		s.addShape(shape)
		return nil
	default:
		return fmt.Errorf("pptx: AddShape: unsupported shape type %T", shape)
	}
}

// addShape appends a shape the sync paths know how to serialize. It first
// materializes the slide (sx) so a shape added to a never-accessed loaded slide
// extends the slide's existing shapes rather than replacing them, and so the
// save regenerates the part (sxModel is now set) instead of passing the
// original bytes through and dropping the addition.
func (s *Slide) addShape(shape Shape) {
	s.sx()
	s.setShapeBackRef(shape)
	s.shapeCache = append(s.shapeCache, shape)
	s.shapesModified = true
}

// RemoveShape removes a shape from the slide. On a slide loaded from a file the
// removed shape's node is deleted surgically from the parsed tree on save, so
// other content (including group shapes, connectors, and other kinds the domain
// model does not represent) is preserved.
func (s *Slide) RemoveShape(shape Shape) {
	s.sx()
	for i, sh := range s.shapeCache {
		if sh != shape {
			continue
		}
		switch {
		case i < s.syncedShapes && i < len(s.shapeRefs):
			// A synced shape: mark its source node for surgical deletion. A
			// sentinel ref (Index -1) means the shape never made it into the
			// tree, so there is nothing to delete there.
			if ref := s.shapeRefs[i]; ref.Index >= 0 {
				s.removedRefs = append(s.removedRefs, ref)
			}
			s.shapeRefs = append(s.shapeRefs[:i], s.shapeRefs[i+1:]...)
			s.syncedShapes--
		case i < s.syncedShapes:
			// Parsed shape without a tracked source (no child-order info):
			// fall back to a full rebuild.
			s.forceShapeRebuild = true
		}
		// Shapes added after the last sync were never written; dropping them
		// from the slice is sufficient.
		s.shapeCache = append(s.shapeCache[:i], s.shapeCache[i+1:]...)
		s.shapesModified = true
		return
	}
}

// AddTextBox adds a text box shape to the slide.
func (s *Slide) AddTextBox() *TextBox {
	tb := NewTextBox()
	s.addShape(tb)
	return tb
}

// AddPicture adds a picture shape to the slide, reading the image from
// imagePath. It returns an error if the file cannot be read (previously the
// path was stored without reading it, so a nonexistent file returned no error
// and produced a blip with no image reference), or if its bytes are not an
// image format this package embeds. The image data is embedded as a media part
// when the presentation is saved.
//
// An .svg file is embedded the way PowerPoint expects an SVG: a transparent
// raster fallback in a:blip@r:embed with the SVG itself referenced through the
// asvg:svgBlip extension, matching docx's Run.AddImage and xlsx's
// Sheet.AddImage. Supply your own fallback with Picture.SetSVGImageData.
//
// The picture frame defaults to the image's intrinsic size at 96 DPI (decoded
// from the PNG/JPEG/GIF header; other formats fall back to 4x3 inches), so the
// picture is visible without further setup. Call SetSize/SetPosition on the
// returned Picture to place it explicitly.
func (s *Slide) AddPicture(imagePath string) (*Picture, error) {
	pic := NewPicture()
	if err := pic.SetImage(imagePath); err != nil {
		return nil, err
	}
	s.sizePictureToImage(pic)
	s.addShape(pic)
	return pic, nil
}

// AddPictureFromBytes adds a picture to the slide from raw image bytes and
// their content type (e.g. "image/png"), embedding the image in the .pptx on
// save. This is the byte-slice counterpart to AddPicture (which reads a file)
// and mirrors AddVideo/AddAudio. The frame defaults to the image's intrinsic
// pixel size at 96 DPI, or 4x3 inches when the dimensions cannot be decoded;
// override it with Picture.SetSize.
//
// It fails with an error when the data is empty or is not one of the image
// formats this package embeds. That check used to be deferred to save and then
// never happened, so garbage bytes under an "image/png" content type saved
// clean and produced an unreadable media part while this godoc promised
// otherwise (C441).
//
// SVG data — either declared with an "image/svg+xml" content type or recognized
// by content — is embedded with a transparent raster fallback and an
// asvg:svgBlip extension, the structure PowerPoint needs. Previously it emitted
// a bare a:blip pointing straight at the .svg part, which most PowerPoint
// versions render as nothing at all, even though docx and xlsx built the
// conformant pair from the same call (C387). Supply your own fallback with
// Picture.SetSVGImageData.
func (s *Slide) AddPictureFromBytes(data []byte, contentType string) (*Picture, error) {
	if len(data) == 0 {
		return nil, fmt.Errorf("pptx: AddPictureFromBytes: image data is empty")
	}
	pic := NewPicture()
	if err := pic.setImageBytes("AddPictureFromBytes", data, contentType); err != nil {
		return nil, err
	}
	s.sizePictureToImage(pic)
	s.addShape(pic)
	return pic, nil
}

// sizePictureToImage gives a freshly added picture its default frame: the
// intrinsic pixel size of the image at 96 DPI, or 4x3 inches when the format
// carries no decodable header. For an SVG the size comes from the SVG root
// rather than from the transparent raster fallback, which is 1x1.
func (s *Slide) sizePictureToImage(pic *Picture) {
	if len(pic.svgData) > 0 {
		w, h := svgIntrinsicSizeEMU(pic.svgData)
		pic.SetSize(w, h)
		return
	}
	if w, h, ok := nativeImageSize(pic.imageData); ok {
		pic.SetSize(w, h)
		return
	}
	pic.SetSize(dml.Inches(4), dml.Inches(3))
}

// AddTable adds a table to the slide.
func (s *Slide) AddTable(rows, cols int) *Table {
	table := NewTable(rows, cols)
	s.addShape(table)
	return table
}

// AddConnector adds a connector (a p:cxnSp connection shape) to the slide and
// returns it for further configuration. Bind its ends to shapes with
// Connect / SetStartShape / SetEndShape (the cNvPr ids are resolved on save,
// so it can target API-created shapes) or place it freely with SetPoints, and
// style its line with SetLine / SetLineWidth / SetLineColor / SetLineDash. The
// connector participates in the shape sync, so it coexists with existing
// shapes and preserved connectors on a loaded slide.
func (s *Slide) AddConnector(kind ConnectorKind) *Connector {
	c := NewConnector(kind)
	s.addShape(c)
	return c
}

// Connectors returns the connectors (p:cxnSp) on the slide, in z-order.
func (s *Slide) Connectors() []*Connector {
	var out []*Connector
	for _, sh := range s.shapeList() {
		if c, ok := sh.(*Connector); ok {
			out = append(out, c)
		}
	}
	return out
}

// AddVideo embeds a video in the slide from raw media bytes and their content
// type (e.g. "video/mp4"). The video is stored inside the .pptx and plays on
// click in PowerPoint. Set a poster image with Video.SetPoster; otherwise a
// placeholder preview is generated on save. An empty contentType is inferred
// from the data's magic bytes; saving fails with an error when the data is
// empty or the content type is neither given nor recognizable.
func (s *Slide) AddVideo(data []byte, contentType string) *Video {
	v := NewVideo(data, contentType)
	s.addShape(v)
	return v
}

// AddAudio embeds an audio clip in the slide from raw media bytes and their
// content type (e.g. "audio/mpeg"). Set an icon image with Audio.SetPoster;
// otherwise a placeholder is generated on save. An empty contentType is
// inferred from the data's magic bytes; saving fails with an error when the
// data is empty or the content type is neither given nor recognizable.
func (s *Slide) AddAudio(data []byte, contentType string) *Audio {
	a := NewAudio(data, contentType)
	s.addShape(a)
	return a
}

// Placeholders returns all placeholder shapes on the slide.
func (s *Slide) Placeholders() []*PlaceholderShape {
	var placeholders []*PlaceholderShape
	for _, shape := range s.shapeList() {
		if ph, ok := shape.(*PlaceholderShape); ok {
			placeholders = append(placeholders, ph)
		}
	}
	return placeholders
}

// Placeholder returns the slide's placeholder of the given type, or
// ErrPlaceholderNotFound when it has none.
//
// It is the error-reporting spelling of GetPlaceholder, matching xlsx's
// SheetByName and pptx's own LayoutByName: a lookup that can miss says so
// rather than handing back a nil pointer to dereference (C565).
func (s *Slide) Placeholder(phType PlaceholderType) (*PlaceholderShape, error) {
	if ph := s.GetPlaceholder(phType); ph != nil {
		return ph, nil
	}
	return nil, fmt.Errorf("%w: type %v on slide %d", ErrPlaceholderNotFound, phType, s.index)
}

// GetPlaceholder returns the placeholder with the specified type, or nil.
//
// Deprecated: use Placeholder, which reports a miss as an error (C565).
func (s *Slide) GetPlaceholder(phType PlaceholderType) *PlaceholderShape {
	for _, shape := range s.shapeList() {
		if ph, ok := shape.(*PlaceholderShape); ok {
			if ph.PlaceholderType() == phType {
				return ph
			}
		}
	}
	return nil
}

// ShapeByName returns the first shape with the given name, or nil if not found.
func (s *Slide) ShapeByName(name string) Shape {
	for _, shape := range s.shapeList() {
		if found := shapeByName(shape, name); found != nil {
			return found
		}
	}
	return nil
}

func shapeByName(shape Shape, name string) Shape {
	if shape.Name() == name {
		return shape
	}
	if group, ok := shape.(*GroupShape); ok {
		for _, child := range group.Children() {
			if found := shapeByName(child, name); found != nil {
				return found
			}
		}
	}
	return nil
}

// TitlePlaceholder returns the title placeholder, or nil if none exists.
func (s *Slide) TitlePlaceholder() *PlaceholderShape {
	return s.GetPlaceholder(PlaceholderTitle)
}

// BodyPlaceholder returns the body/content placeholder, or nil if none exists.
func (s *Slide) BodyPlaceholder() *PlaceholderShape {
	return s.GetPlaceholder(PlaceholderBody)
}

// marshal converts the slide to XML bytes. It regenerates the part from the
// (possibly edited) model; the save path calls it only for a slide whose model
// was materialized, so an untouched slide passes its original bytes through
// without ever reaching here.
func (s *Slide) marshal() ([]byte, error) {
	// materialize, not ensureModel: serializing a slide is not editing it, and
	// ensureModel would record a model edit for every slide on every save.
	s.materialize()

	// Reject media that cannot become a valid package part (no data, or no
	// recognizable content type) before any of it is written.
	if err := s.validateMediaShapes(); err != nil {
		return nil, err
	}

	// Only sync Go shapes to XML when shapes were modified via the API: added
	// or removed (shapesModified), or mutated in place (dirty flags). When
	// loading from a file, the slideXML already contains the parsed shapes.
	if s.shapesModified || s.hasDirtyShapes() {
		s.syncShapesToXML()
	}

	// Process any pending image replacements after the XML tree is up to date.
	// This modifies the XML directly, converting p:sp elements to p:pic elements
	// or swapping the blip reference on existing pictures.
	if err := s.processPendingImages(); err != nil {
		return nil, err
	}

	// Build the timing tree for any auto-play media added to the slide (needs the
	// shape ids assigned during the sync above).
	s.applyMediaTiming()

	// Flush any authored animations into the timing tree (also after the sync,
	// so build-by-paragraph can count the target's paragraphs).
	s.applyAnimations()

	// Use the namespace-aware marshaler for PowerPoint compatibility
	return marshalSlide(s.sx())
}

// syncShapesToXML converts Go shapes to oxml types in the shape tree.
func (s *Slide) syncShapesToXML() {
	// Sniff missing media content types first: syncs triggered before the
	// first save (ReplaceText, Duplicate) embed media parts too.
	s.resolveMediaContentTypes()
	// Allocate the relationships API-created hyperlinks need before any shape is
	// marshaled, so their r:id is present when runToOxml / the shape builders
	// emit the a:hlinkClick. Idempotent: hyperlinks already backed by a rel are
	// left alone.
	s.allocateHyperlinkRels()
	if s.sx().CSld == nil {
		s.sx().CSld = &oxml.CommonSlideData{}
	}
	if s.sx().CSld.SpTree == nil {
		s.sx().CSld.SpTree = newShapeTree()
	}

	spTree := s.sx().CSld.SpTree

	// Loaded slide with removals: delete just the removed nodes from the parsed
	// tree (preserving all other content, including kinds the domain model does
	// not represent), then append any new shapes. Avoids the destructive full
	// rebuild below.
	if len(s.removedRefs) > 0 && !s.forceShapeRebuild {
		// Capture what the removed pic nodes reference before they go: their
		// shape ids (a generated timing tree must stop targeting them) and
		// their relationship ids (media/poster rels to garbage collect).
		removedSpids, removedRelIDs := collectRemovedPicRefs(spTree, s.removedRefs)
		spTree.RemoveChildren(s.removedRefs)
		s.reindexShapeRefsAfterRemoval(s.removedRefs)
		s.removedRefs = nil
		s.syncDirtyShapes(spTree)
		if len(s.shapeCache) > s.syncedShapes {
			s.appendShapesToXML(spTree, s.shapeCache[s.syncedShapes:])
		}
		s.pruneAutoTiming(removedSpids)
		s.gcSlideRels(removedRelIDs)
		s.resolveConnectorBindings()
		s.syncedShapes = len(s.shapeCache)
		s.shapesModified = false
		s.clearShapeDirt()
		return
	}

	// Loaded slide, in-place edits and appends only: flush dirty synced shapes
	// into their parsed nodes, then marshal just the new shapes into the parsed
	// tree. The full rebuild below regenerates the tree from the domain model,
	// which drops content the model does not represent (group shapes,
	// connectors) and re-numbers every existing shape — acceptable for decks
	// built programmatically, destructive for decks loaded from a file.
	if s.syncedShapes > 0 && !s.forceShapeRebuild && len(s.shapeCache) >= s.syncedShapes {
		s.syncDirtyShapes(spTree)
		s.appendShapesToXML(spTree, s.shapeCache[s.syncedShapes:])
		s.resolveConnectorBindings()
		s.syncedShapes = len(s.shapeCache)
		s.shapesModified = false
		s.clearShapeDirt()
		return
	}

	// Clear existing shapes and child order tracking. Connectors are cleared
	// too: they are materialized into s.shapeCache and re-emitted from the loop
	// below, so leaving the parsed nodes would duplicate them.
	spTree.Sp = nil
	spTree.GraphicFrame = nil
	spTree.Pic = nil
	spTree.GrpSp = nil
	spTree.CxnSp = nil
	spTree.ClearChildOrder()

	// The rebuild renumbers every shape and re-collects auto-play refs from
	// scratch via buildMediaPic below, so drop refs gathered by earlier syncs
	// (they hold stale ids and would duplicate media in the timing tree) and
	// flag any generated timing tree for regeneration.
	s.autoplayMedia = nil
	s.timingRegen = true

	// Convert each shape, seeding ids above anything the rebuild left in the
	// tree (AltContent/RawXML children keep their parsed ids): cNvPr ids must be
	// unique slide-wide (ST_DrawingElementId).
	shapeID := spTree.MaxShapeID() + 1
	if shapeID < 2 {
		shapeID = 2 // 1 belongs to the shape tree itself
	}
	allocID := func() uint32 {
		id := shapeID
		shapeID++
		return id
	}
	for _, shape := range s.shapeCache {
		// Record the id assigned to each shape so a connector bound to it can
		// resolve its cNvPr id after the loop (see resolveConnectorBindings) and
		// so ID() reports the saved id in-memory. Groups and connectors set their
		// own sourceID inside their builders.
		switch sh := shape.(type) {
		case *TextBox:
			id := allocID()
			spTree.Sp = append(spTree.Sp, textBoxToOxml(sh, id))
			sh.sourceID = id
		case *PlaceholderShape:
			id := allocID()
			spTree.Sp = append(spTree.Sp, placeholderToOxml(sh, id))
			sh.sourceID = id
		case *AutoShape:
			id := allocID()
			spTree.Sp = append(spTree.Sp, autoShapeToOxml(sh, id))
			sh.sourceID = id
		case *Table:
			id := allocID()
			spTree.GraphicFrame = append(spTree.GraphicFrame, tableToOxml(sh, id))
			sh.sourceID = id
		case *ChartFrame:
			id := allocID()
			spTree.GraphicFrame = append(spTree.GraphicFrame, chartFrameToOxml(sh, id))
			sh.sourceID = id
		case *SmartArtFrame:
			id := allocID()
			spTree.GraphicFrame = append(spTree.GraphicFrame, smartArtFrameToOxml(sh, id))
			sh.sourceID = id
		case *OLEObjectFrame:
			id := allocID()
			spTree.GraphicFrame = append(spTree.GraphicFrame, oleObjectFrameToOxml(sh, id))
			sh.sourceID = id
		case *Picture:
			id := allocID()
			spTree.Pic = append(spTree.Pic, pictureToOxml(sh, id))
			sh.sourceID = id
		case *Video:
			id := allocID()
			spTree.Pic = append(spTree.Pic, s.buildMediaPic(&sh.mediaShape, id, mediaVideo))
			sh.sourceID = id
		case *Audio:
			id := allocID()
			spTree.Pic = append(spTree.Pic, s.buildMediaPic(&sh.mediaShape, id, mediaAudio))
			sh.sourceID = id
		case *GroupShape:
			// A domain-built group serializes as a real p:grpSp with its
			// children, ids allocated slide-wide (previously groups added via
			// AddShape were silently never written, C85).
			spTree.GrpSp = append(spTree.GrpSp, s.buildGroupNode(sh, allocID))
		case *Connector:
			spTree.CxnSp = append(spTree.CxnSp, connectorToOxml(sh, allocID()))
		}
	}

	// Every shape now has its assigned id, so connectors bound to shapes can
	// write their stCxn/endCxn (see resolveConnectorBindings).
	s.resolveConnectorBindings()

	// The rebuild regenerated the tree from the domain model, so media/image
	// relationships belonging to shapes that are gone are no longer referenced
	// by the slide XML — drop them so their parts can be garbage-collected at
	// save time (C221). gcSlideRels keeps every id the regenerated XML still
	// references.
	if s.partName != "" && s.presentation != nil {
		var removable []string
		for _, rel := range s.presentation.relationships[s.partName] {
			if rel != nil && removableRelType(rel.Type) {
				removable = append(removable, rel.ID)
			}
		}
		s.gcSlideRels(removable)
	}

	// The rebuild regenerates the whole tree from the domain model, so any
	// surgical bookkeeping recorded against the old tree is void. Leaving
	// syncedShapes at 0 keeps the slide in rebuild mode, where every domain
	// mutation is flushed on the next sync.
	s.syncedShapes = 0
	s.shapeRefs = nil
	s.removedRefs = nil
	s.shapesModified = false
	s.clearShapeDirt()
}

// resolveConnectorBindings writes the stCxn/endCxn bindings of API-created
// connectors into their parsed nodes, now that every shape on the slide has an
// id. A connector bound to a shape (via Connect/SetStartShape/SetEndShape)
// takes that shape's assigned cNvPr id; ends left free, and connectors
// materialized from a file (whose bindings are already in their nodes), are
// untouched — so an unmodified deck with existing connectors stays
// byte-identical.
func (s *Slide) resolveConnectorBindings() {
	// Connectors can live at the slide top level or inside a group
	// (GroupShape.AddConnector); forEachShape descends into groups so a grouped
	// connector's endpoint bindings resolve to the same assigned ids.
	forEachShape(s.shapeCache, func(sh Shape) {
		c, ok := sh.(*Connector)
		if !ok || c.sourceCxn == nil || c.sourceCxn.NvCxnSpPr == nil {
			return
		}
		if c.startShape == nil && c.endShape == nil {
			return
		}
		cnv := c.sourceCxn.NvCxnSpPr.CNvCxnSpPr
		if cnv == nil {
			cnv = &dml.CNvCxnSpPr{}
			c.sourceCxn.NvCxnSpPr.CNvCxnSpPr = cnv
		}
		if c.startShape != nil {
			if id := c.startShape.ID(); id != 0 {
				cnv.StCxn = &dml.Cxn{Id: id, Idx: c.startSite}
			}
		}
		if c.endShape != nil {
			if id := c.endShape.ID(); id != 0 {
				cnv.EndCxn = &dml.Cxn{Id: id, Idx: c.endSite}
			}
		}
	})
}

// reindexShapeRefsAfterRemoval rewrites shapeRefs from the pre-compaction
// indices they were recorded with to the indices the surviving children occupy
// after RemoveChildren compacted the typed slices: every removed same-kind
// child below a ref shifts it down by one. Without this, refs recorded before
// one removal target the wrong nodes in the next removal cycle.
func (s *Slide) reindexShapeRefsAfterRemoval(removed []oxml.ChildRef) {
	for i, ref := range s.shapeRefs {
		if ref.Index < 0 {
			continue
		}
		dec := 0
		for _, rem := range removed {
			if rem.Kind == ref.Kind && rem.Index < ref.Index {
				dec++
			}
		}
		if dec > 0 {
			s.shapeRefs[i] = oxml.ChildRef{Kind: ref.Kind, Index: ref.Index - dec}
		}
	}
}

// appendShapesToXML marshals newly added shapes into a parsed shape tree,
// assigning ids above everything already on the slide. Each appended shape's
// child reference is recorded in shapeRefs so a later removal (or in-place
// update) can target its node surgically instead of forcing a full rebuild;
// shapes the append path cannot express get a sentinel ref (Index -1) to keep
// shapeRefs aligned with the shapes slice.
func (s *Slide) appendShapesToXML(spTree *oxml.ShapeTree, shapes []Shape) {
	id := spTree.MaxShapeID() + 1
	if id < 2 {
		id = 2 // 1 belongs to the shape tree itself
	}
	allocID := func() uint32 {
		next := id
		id++
		return next
	}
	for _, shape := range shapes {
		ref := oxml.ChildRef{Index: -1}
		switch sh := shape.(type) {
		case *TextBox:
			spTree.AppendSp(textBoxToOxml(sh, id))
			ref = oxml.ChildRef{Kind: oxml.ChildSp, Index: len(spTree.Sp) - 1}
		case *PlaceholderShape:
			spTree.AppendSp(placeholderToOxml(sh, id))
			ref = oxml.ChildRef{Kind: oxml.ChildSp, Index: len(spTree.Sp) - 1}
		case *AutoShape:
			spTree.AppendSp(autoShapeToOxml(sh, id))
			ref = oxml.ChildRef{Kind: oxml.ChildSp, Index: len(spTree.Sp) - 1}
		case *Table:
			gf := tableToOxml(sh, id)
			spTree.AppendGraphicFrame(gf)
			// Later row/cell mutations are auto-flushed into this frame on save
			// (SyncXML forces the flush earlier but is not required).
			sh.sourceFrame = gf
			ref = oxml.ChildRef{Kind: oxml.ChildGraphicFrame, Index: len(spTree.GraphicFrame) - 1}
		case *ChartFrame:
			spTree.AppendGraphicFrame(chartFrameToOxml(sh, id))
			ref = oxml.ChildRef{Kind: oxml.ChildGraphicFrame, Index: len(spTree.GraphicFrame) - 1}
		case *SmartArtFrame:
			spTree.AppendGraphicFrame(smartArtFrameToOxml(sh, id))
			ref = oxml.ChildRef{Kind: oxml.ChildGraphicFrame, Index: len(spTree.GraphicFrame) - 1}
		case *OLEObjectFrame:
			spTree.AppendGraphicFrame(oleObjectFrameToOxml(sh, id))
			ref = oxml.ChildRef{Kind: oxml.ChildGraphicFrame, Index: len(spTree.GraphicFrame) - 1}
		case *Picture:
			spTree.AppendPic(pictureToOxml(sh, id))
			ref = oxml.ChildRef{Kind: oxml.ChildPic, Index: len(spTree.Pic) - 1}
		case *Video:
			spTree.AppendPic(s.buildMediaPic(&sh.mediaShape, id, mediaVideo))
			ref = oxml.ChildRef{Kind: oxml.ChildPic, Index: len(spTree.Pic) - 1}
		case *Audio:
			spTree.AppendPic(s.buildMediaPic(&sh.mediaShape, id, mediaAudio))
			ref = oxml.ChildRef{Kind: oxml.ChildPic, Index: len(spTree.Pic) - 1}
		case *GroupShape:
			// Serialize a domain-built group appended to a loaded slide as a
			// real p:grpSp (previously a sentinel ref: silently never written,
			// C85). buildGroupNode allocates the ids itself, so the post-switch
			// id++ is skipped via continue-style handling below.
			spTree.AppendGrpSp(s.buildGroupNode(sh, allocID))
			s.shapeRefs = append(s.shapeRefs, oxml.ChildRef{Kind: oxml.ChildGrpSp, Index: len(spTree.GrpSp) - 1})
			continue
		case *Connector:
			spTree.AppendCxnSp(connectorToOxml(sh, id))
			ref = oxml.ChildRef{Kind: oxml.ChildCxnSp, Index: len(spTree.CxnSp) - 1}
		}
		if ref.Index >= 0 {
			// Record the assigned id on the shape so a connector bound to it can
			// resolve its cNvPr id, and so ID() reports the saved id in-memory.
			if b := baseShapeOf(shape); b != nil {
				b.sourceID = id
			}
			id++
		}
		s.shapeRefs = append(s.shapeRefs, ref)
	}
}

// textBoxToOxml converts a TextBox to oxml.Shape.
func textBoxToOxml(tb *TextBox, id uint32) *oxml.Shape {
	name := tb.Name()
	if name == "" {
		name = "TextBox"
	}

	x, y := tb.Position()
	w, h := tb.Size()

	sp := &oxml.Shape{
		NvSpPr: &oxml.NvSpPr{
			CNvPr: &dml.CNvPr{
				Id:   id,
				Name: name,
			},
			CNvSpPr: &dml.CNvSpPr{
				TxBox: true,
			},
			NvPr: &oxml.NvPr{},
		},
		SpPr: &dml.SpPr{
			Xfrm: &dml.Xfrm{
				Off: &dml.OffXML{X: int64(x), Y: int64(y)},
				Ext: &dml.ExtXML{Cx: int64(w), Cy: int64(h)},
			},
			PrstGeom: &dml.PrstGeom{
				Prst:  "rect",
				AvLst: &dml.AvLst{},
			},
		},
	}

	// Carry any fill/line/shadow set via SetFill/SetLine/SetShadow into the XML
	// (previously textBoxToOxml ignored tb.spPr entirely, so those setters were
	// silent no-ops).
	applyShapeStyle(sp.SpPr, &tb.spPr)

	if tb.hyperlink != nil {
		sp.NvSpPr.CNvPr.HlinkClick = hyperlinkToXML(tb.hyperlink)
	}

	if tb.textFrame != nil {
		sp.TxBody = textFrameToOxml(tb.textFrame)
	}

	return sp
}

// applyShapeStyle copies the fill, line, and effect properties that a domain
// shape stored (via Fill/Line/Shadow ApplyToSpPr) into the SpPr being
// marshaled. Every fill kind is copied, not just SolidFill, so gradient,
// pattern, and no-fill values are not dropped.
// mergeLn overlays the line members the domain model represents (width, cap,
// compound, alignment, fill, dash) onto the parsed a:ln and returns it.
//
// Assigning src wholesale — which is what SetLineWidth/SetLineColor/SetLineDash
// and Connector.SetLine used to cause — replaced the parsed line with the three
// properties dml.Line models, so a connector with cap="rnd" and a:headEnd /
// a:tailEnd lost both arrowheads and its cap on a width change. Arrowheads are
// the normal case for connectors, and the same path styles AutoShape and
// TextBox lines (C417).
func mergeLn(dst, src *dml.Ln) *dml.Ln {
	if dst == nil {
		return src
	}
	if src.W != nil {
		dst.W = src.W
	}
	if src.Cap != "" {
		dst.Cap = src.Cap
	}
	if src.Cmpd != "" {
		dst.Cmpd = src.Cmpd
	}
	if src.Algn != "" {
		dst.Algn = src.Algn
	}
	// The line fill is an exclusive choice, so a set member replaces the whole
	// group rather than joining it.
	if src.NoFill != nil || src.SolidFill != nil || src.GradFill != nil || src.PattFill != nil {
		dst.NoFill, dst.SolidFill, dst.GradFill, dst.PattFill = nil, nil, nil, nil
		switch {
		case src.NoFill != nil:
			dst.NoFill = src.NoFill
		case src.SolidFill != nil:
			dst.SolidFill = src.SolidFill
		case src.GradFill != nil:
			dst.GradFill = src.GradFill
		case src.PattFill != nil:
			dst.PattFill = src.PattFill
		}
	}
	// So is the dash: a preset dash displaces a parsed custom one.
	if src.PrstDash != nil {
		dst.PrstDash, dst.CustDash = src.PrstDash, nil
	} else if src.CustDash != nil {
		dst.PrstDash, dst.CustDash = nil, src.CustDash
	}
	// And the join.
	if src.Round != nil || src.Bevel != nil || src.Miter != nil {
		dst.Round, dst.Bevel, dst.Miter = src.Round, src.Bevel, src.Miter
	}
	if src.HeadEnd != nil {
		dst.HeadEnd = src.HeadEnd
	}
	if src.TailEnd != nil {
		dst.TailEnd = src.TailEnd
	}
	if src.ExtLst != nil {
		dst.ExtLst = src.ExtLst
	}
	return dst
}

func applyShapeStyle(dst *dml.SpPr, src *dml.SpPr) {
	if src == nil {
		return
	}
	// Fill is an exclusive choice (EG_FillProperties): a shape carries at most
	// one fill element. When the overlay sets any fill member it replaces the
	// destination's fill atomically — clear every competing member first, so a
	// shape parsed with <a:noFill/> that is given a solid fill does not end up
	// with both (which is schema-invalid).
	if srcHasFill(src) {
		dst.NoFill, dst.SolidFill, dst.GradFill = nil, nil, nil
		dst.PattFill, dst.BlipFill, dst.GrpFill = nil, nil, nil
		switch {
		case src.NoFill != nil:
			dst.NoFill = src.NoFill
		case src.SolidFill != nil:
			dst.SolidFill = src.SolidFill
		case src.GradFill != nil:
			dst.GradFill = src.GradFill
		case src.PattFill != nil:
			dst.PattFill = src.PattFill
		case src.BlipFill != nil:
			dst.BlipFill = src.BlipFill
		case src.GrpFill != nil:
			dst.GrpFill = src.GrpFill
		}
	}
	if src.Ln != nil {
		dst.Ln = mergeLn(dst.Ln, src.Ln)
	}
	// Effects merge per member: the overlay starts empty for a materialized
	// shape, so setting one effect (glow, shadow, reflection, soft edge) must
	// add to — never replace — the effects already parsed on the node.
	if src.EffectLst != nil {
		mergeEffectLst(dst, src.EffectLst)
	}
	if src.EffectDag != nil {
		dst.EffectDag = src.EffectDag
	}
	if src.Scene3d != nil {
		dst.Scene3d = src.Scene3d
	}
	// sp3d (3D bevel) merges per member for the same reason as the effect list.
	if src.Sp3d != nil {
		mergeSp3d(dst, src.Sp3d)
	}
}

// srcHasFill reports whether the SpPr carries any member of the EG_FillProperties
// exclusive choice.
func srcHasFill(sp *dml.SpPr) bool {
	return sp.NoFill != nil || sp.SolidFill != nil || sp.GradFill != nil ||
		sp.PattFill != nil || sp.BlipFill != nil || sp.GrpFill != nil
}

// mergeEffectLst copies each effect set on src onto dst's effect list,
// allocating one when absent. Members src does not set are left as parsed, so
// setting one effect does not drop effects already on the shape.
func mergeEffectLst(dst *dml.SpPr, src *dml.EffectLst) {
	if dst.EffectLst == nil {
		dst.EffectLst = &dml.EffectLst{}
	}
	d := dst.EffectLst
	if src.Blur != nil {
		d.Blur = src.Blur
	}
	if src.FillOverlay != nil {
		d.FillOverlay = src.FillOverlay
	}
	if src.Glow != nil {
		d.Glow = src.Glow
	}
	if src.InnerShdw != nil {
		d.InnerShdw = src.InnerShdw
	}
	if src.OuterShdw != nil {
		d.OuterShdw = src.OuterShdw
	}
	if src.PrstShdw != nil {
		d.PrstShdw = src.PrstShdw
	}
	if src.Reflection != nil {
		d.Reflection = src.Reflection
	}
	if src.SoftEdge != nil {
		d.SoftEdge = src.SoftEdge
	}
}

// mergeSp3d copies each 3D property set on src onto dst's sp3d, allocating one
// when absent. Properties src does not set are left as parsed, so setting one
// (e.g. a top bevel) does not drop 3D properties already on the shape.
func mergeSp3d(dst *dml.SpPr, src *dml.Sp3d) {
	if dst.Sp3d == nil {
		dst.Sp3d = src
		return
	}
	d := dst.Sp3d
	if src.Z != 0 {
		d.Z = src.Z
	}
	if src.ExtrusionH != 0 {
		d.ExtrusionH = src.ExtrusionH
	}
	if src.ContourW != 0 {
		d.ContourW = src.ContourW
	}
	if src.PrstMaterial != "" {
		d.PrstMaterial = src.PrstMaterial
	}
	if src.BevelT != nil {
		d.BevelT = src.BevelT
	}
	if src.BevelB != nil {
		d.BevelB = src.BevelB
	}
	if src.ExtrusionClr != nil {
		d.ExtrusionClr = src.ExtrusionClr
	}
	if src.ContourClr != nil {
		d.ContourClr = src.ContourClr
	}
}

// placeholderToOxml converts a PlaceholderShape to oxml.Shape.
func placeholderToOxml(ph *PlaceholderShape, id uint32) *oxml.Shape {
	name := ph.Name()
	if name == "" {
		name = string(ph.phType)
	}

	sp := &oxml.Shape{
		NvSpPr: &oxml.NvSpPr{
			CNvPr: &dml.CNvPr{
				Id:   id,
				Name: name,
			},
			CNvSpPr: &dml.CNvSpPr{},
			NvPr: &oxml.NvPr{
				Ph: &oxml.Placeholder{
					Type:   string(ph.phType),
					Orient: string(ph.orientation),
					Sz:     string(ph.size),
					Idx:    ph.idx,
				},
			},
		},
		SpPr: &dml.SpPr{},
	}

	// Furniture placeholders (footer/number/date) omit xfrm so PowerPoint
	// inherits geometry from the layout placeholder of the same type; every
	// other placeholder carries its explicit position and size.
	if !ph.inheritGeometry {
		x, y := ph.Position()
		w, h := ph.Size()
		sp.SpPr.Xfrm = &dml.Xfrm{
			Off: &dml.OffXML{X: int64(x), Y: int64(y)},
			Ext: &dml.ExtXML{Cx: int64(w), Cy: int64(h)},
		}
	}

	if ph.hyperlink != nil {
		sp.NvSpPr.CNvPr.HlinkClick = hyperlinkToXML(ph.hyperlink)
	}

	switch {
	case ph.fieldType != "":
		sp.TxBody = fieldTextBody(ph.fieldType, ph.fieldText)
	case ph.textFrame != nil:
		sp.TxBody = textFrameToOxml(ph.textFrame)
	}

	return sp
}

// fieldGUIDs are stable per-field-type ids for the required a:fld id
// attribute. PowerPoint uses random GUIDs but does not require uniqueness
// across slides for these auto fields; fixed values keep spine's output
// deterministic.
var fieldGUIDs = map[string]string{
	"slidenum": "{4A9C4C6E-5B2A-4C1D-9E8F-1A2B3C4D5E6F}",
	"datetime": "{7B1D2E3F-4A5B-4C6D-8E9F-0A1B2C3D4E5F}",
}

// fieldTextBody builds a text body whose single paragraph is an auto-updating
// field (a:fld) — used by slide-number and date furniture placeholders. The
// fallback text is what PowerPoint shows until it recalculates the field.
func fieldTextBody(fieldType, fallback string) *dml.TxBody {
	id := fieldGUIDs[fieldType]
	if id == "" {
		id = "{00000000-0000-0000-0000-000000000000}"
	}
	return &dml.TxBody{
		BodyPr:   &dml.BodyPr{},
		LstStyle: &dml.LstStyle{},
		P: []*dml.P{{
			Fld: []*dml.Fld{{Id: id, Type: fieldType, T: fallback}},
		}},
	}
}

// autoShapeToOxml converts an AutoShape to oxml.Shape.
func autoShapeToOxml(as *AutoShape, id uint32) *oxml.Shape {
	name := as.Name()
	if name == "" {
		name = "Shape"
	}

	x, y := as.Position()
	w, h := as.Size()

	sp := &oxml.Shape{
		NvSpPr: &oxml.NvSpPr{
			CNvPr: &dml.CNvPr{
				Id:   id,
				Name: name,
			},
			CNvSpPr: &dml.CNvSpPr{},
			NvPr:    &oxml.NvPr{},
		},
		SpPr: &dml.SpPr{
			Xfrm: &dml.Xfrm{
				Off: &dml.OffXML{X: int64(x), Y: int64(y)},
				Ext: &dml.ExtXML{Cx: int64(w), Cy: int64(h)},
			},
			PrstGeom: &dml.PrstGeom{
				Prst:  as.presetGeometry,
				AvLst: &dml.AvLst{},
			},
		},
	}
	// Copy every fill kind plus line/effects (previously only SolidFill was
	// carried, so gradient/pattern/no-fill fills set via SetFill were dropped).
	applyShapeStyle(sp.SpPr, &as.spPr)

	if as.hyperlink != nil {
		sp.NvSpPr.CNvPr.HlinkClick = hyperlinkToXML(as.hyperlink)
	}

	if as.textFrame != nil {
		sp.TxBody = textFrameToOxml(as.textFrame)
	}

	return sp
}

// textFrameToOxml converts a TextFrame to dml.TxBody.
func textFrameToOxml(tf *TextFrame) *dml.TxBody {
	lIns := int64(tf.margins.Left)
	tIns := int64(tf.margins.Top)
	rIns := int64(tf.margins.Right)
	bIns := int64(tf.margins.Bottom)
	txBody := &dml.TxBody{
		BodyPr: &dml.BodyPr{
			Wrap:   string(tf.wrap),
			Anchor: string(tf.anchor),
			LIns:   &lIns,
			TIns:   &tIns,
			RIns:   &rIns,
			BIns:   &bIns,
		},
		LstStyle: &dml.LstStyle{},
		P:        make([]*dml.P, 0, len(tf.paragraphs)),
	}
	applyAutofit(txBody.BodyPr, tf.autofit)

	for _, para := range tf.paragraphs {
		ap := paragraphToOxml(para)
		txBody.P = append(txBody.P, ap)
	}

	// Ensure at least one paragraph
	if len(txBody.P) == 0 {
		txBody.P = append(txBody.P, &dml.P{})
	}

	return txBody
}

// paragraphToOxml converts a Paragraph to dml.P.
func paragraphToOxml(p *Paragraph) *dml.P {
	ap := &dml.P{
		R: make([]*dml.R, 0, len(p.runs)),
	}

	// Set paragraph properties if needed. An explicitly-set zero counts: the
	// caller asking for "no space before" must reach the XML, since omitting the
	// element means "inherit" (C518).
	needSpacing := p.lineSpacing != 0 || p.spaceBefore != 0 || p.spaceAfter != 0 ||
		p.isSet(paraPropSpaceBefore|paraPropSpaceAfter)
	needBulletStyle := p.bulletColor != nil || p.bulletSizePct != 0 || p.bulletFont != ""
	needIndent := p.marL != nil || p.indent != nil || len(p.tabStops) > 0
	if p.alignment != "" || p.level > 0 || p.isSet(paraPropLevel) ||
		p.bulletType != BulletInherit || needSpacing || needBulletStyle || needIndent {
		ap.PPr = &dml.PPr{
			MarL:   p.marL,
			Indent: p.indent,
			Algn:   string(p.alignment),
		}

		// Emit lvl only when the paragraph is actually at a nonzero level or the
		// caller set one explicitly. Emitting lvl="0" unconditionally put an
		// attribute on every regenerated paragraph that the source never carried
		// (C517).
		if p.level > 0 || p.isSet(paraPropLevel) {
			lvl := int32(p.level)
			ap.PPr.Lvl = &lvl
		}

		// Bullet styling (color/size/font) applies to whichever bullet kind the
		// paragraph carries, so it is emitted independently of the bullet type.
		if p.bulletColor != nil {
			ap.PPr.BuClr = colorToBuClr(p.bulletColor)
		}
		if p.bulletSizePct != 0 {
			ap.PPr.BuSzPct = &dml.BuSzPct{Val: dml.NewPercentage(p.bulletSizePct)}
		}
		if p.bulletFont != "" {
			ap.PPr.BuFont = &dml.BuFont{Typeface: p.bulletFont}
		}

		// Emit a bullet element only when the bullet was set explicitly.
		// BulletInherit (the default) emits nothing so the paragraph keeps the
		// layout/master bullet even when other properties (alignment, spacing)
		// are set.
		applyBulletKind(ap.PPr, p)

		ap.PPr.TabLst = tabStopsToOxml(p.tabStops)

		// Spacing (symmetric with the oxml->domain read): line spacing is a
		// percentage, space before/after are point values. An explicit zero set
		// through the setter is emitted rather than suppressed, so "no space
		// before this paragraph" is expressible and does not silently inherit
		// (C518); line spacing keeps its documented 0 == inherit meaning.
		if p.lineSpacing != 0 {
			ap.PPr.LnSpc = &dml.LnSpc{SpcPct: &dml.SpcPct{Val: dml.NewPercentage(p.lineSpacing)}}
		}
		if p.spaceBefore != 0 || p.isSet(paraPropSpaceBefore) {
			ap.PPr.SpcBef = &dml.SpcBef{SpcPts: &dml.SpcPts{Val: int32(p.spaceBefore)}}
		}
		if p.spaceAfter != 0 || p.isSet(paraPropSpaceAfter) {
			ap.PPr.SpcAft = &dml.SpcAft{SpcPts: &dml.SpcPts{Val: int32(p.spaceAfter)}}
		}
	}

	// Convert runs
	for _, run := range p.runs {
		ar := runToOxml(run)
		ap.R = append(ap.R, ar)
	}

	return ap
}

// runToOxml converts a Run to dml.R.
func runToOxml(r *Run) *dml.R {
	ar := &dml.R{
		T: r.text,
	}

	// Set run properties if any formatting is applied. An explicitly-set false
	// counts: omitting b/i means "inherit", so a run the caller un-bolded must
	// still emit b="0" or it re-inherits bold from its placeholder (C518).
	if r.fontName != "" || r.fontSize > 0 || r.bold || r.italic ||
		r.underline != "" || r.strike != "" || r.color != nil || r.baseline != 0 ||
		r.highlight != nil || r.isSet(runPropBold|runPropItalic) {
		ar.RPr = &dml.RPr{}

		if r.highlight != nil {
			ar.RPr.Highlight = colorToColorChoiceOxml(r.highlight)
		}

		if r.fontSize > 0 {
			ar.RPr.Sz = int32(r.fontSize * 100) // Convert points to hundredths
		}

		if r.bold || r.isSet(runPropBold) {
			b := r.bold
			ar.RPr.B = &b
		}

		if r.italic || r.isSet(runPropItalic) {
			i := r.italic
			ar.RPr.I = &i
		}

		if r.underline != "" {
			ar.RPr.U = string(r.underline)
		}

		if r.strike != "" {
			ar.RPr.Strike = string(r.strike)
		}

		if r.baseline != 0 {
			baseline := dml.NewPercentage(r.baseline)
			ar.RPr.Baseline = &baseline
		}

		if r.fontName != "" {
			ar.RPr.Latin = &dml.TextFont{Typeface: r.fontName}
		}

		if r.color != nil {
			ar.RPr.SolidFill = colorToOxml(r.color)
		}
	}

	// A hyperlink lives in a:hlinkClick on the run properties, so it needs an
	// rPr even when no other formatting is set.
	if r.hyperlink != nil {
		if ar.RPr == nil {
			ar.RPr = &dml.RPr{}
		}
		ar.RPr.HlinkClick = hyperlinkToXML(r.hyperlink)
	}

	return ar
}

// applyAutofit sets the body's autofit child to match the domain mode, clearing
// the others first. AutofitInherit leaves all three unset so the body inherits.
func applyAutofit(bp *dml.BodyPr, autofit AutofitType) {
	bp.NoAutofit, bp.NormAutofit, bp.SpAutoFit = nil, nil, nil
	switch autofit {
	case AutofitNone:
		bp.NoAutofit = &dml.NoAutofit{}
	case AutofitShape:
		bp.SpAutoFit = &dml.SpAutoFit{}
	case AutofitNormal:
		bp.NormAutofit = &dml.NormAutofit{}
	}
}

// colorToBuClr converts a Color to a dml.BuClr (a:buClr bullet color).
func colorToBuClr(c *dml.Color) *dml.BuClr {
	if c == nil {
		return nil
	}
	bc := &dml.BuClr{}
	if c.Type == dml.ColorTypeTheme {
		bc.SchemeClr = &dml.SchemeClrTransform{Val: c.Theme.String()}
	} else {
		bc.SrgbClr = &dml.SrgbClr{Val: c.RGB.String()}
	}
	return bc
}

// buClrToColor converts a dml.BuClr bullet color to a dml.Color.
func buClrToColor(bc *dml.BuClr) *dml.Color {
	if bc == nil {
		return nil
	}
	if bc.SrgbClr != nil {
		if rgb, err := dml.ParseRGB(bc.SrgbClr.Val); err == nil {
			c := rgb.ToColor()
			return &c
		}
	}
	if bc.SchemeClr != nil {
		c := parseThemeColorString(bc.SchemeClr.Val).ToColor()
		return &c
	}
	return nil
}

// colorToColorChoiceOxml converts a Color to a dml.ColorChoice (used where the
// schema expects a bare color element, e.g. a:highlight).
func colorToColorChoiceOxml(c *dml.Color) *dml.ColorChoice {
	if c == nil {
		return nil
	}
	cc := &dml.ColorChoice{}
	if c.Type == dml.ColorTypeTheme {
		cc.SchemeClr = &dml.SchemeClrTransform{Val: c.Theme.String()}
	} else {
		cc.SrgbClr = &dml.SrgbClr{Val: c.RGB.String()}
	}
	return cc
}

// colorToOxml converts a Color to dml.SolidFill.
func colorToOxml(c *dml.Color) *dml.SolidFill {
	if c == nil {
		return nil
	}

	sf := &dml.SolidFill{}
	if c.Type == dml.ColorTypeTheme {
		sf.SchemeClr = &dml.SchemeClrTransform{Val: c.Theme.String()}
	} else {
		sf.SrgbClr = &dml.SrgbClr{Val: c.RGB.String()}
	}
	return sf
}

// tableToOxml converts a Table to oxml.GraphicFrame.
func tableToOxml(t *Table, id uint32) *oxml.GraphicFrame {
	name := t.Name()
	if name == "" {
		name = "Table"
	}

	x, y := t.Position()
	w, h := t.Size()

	gf := &oxml.GraphicFrame{
		NvGraphicFramePr: &oxml.NvGraphicFramePr{
			CNvPr: &dml.CNvPr{
				Id:   id,
				Name: name,
			},
			CNvGraphicFramePr: &oxml.CNvGraphicFramePr{
				GraphicFrameLocks: &oxml.GraphicFrameLocks{NoGrp: true},
			},
			NvPr: &oxml.NvPr{},
		},
		Xfrm: &dml.Xfrm{
			Off: &dml.OffXML{X: int64(x), Y: int64(y)},
			Ext: &dml.ExtXML{Cx: int64(w), Cy: int64(h)},
		},
		Graphic: &oxml.AGraphic{
			GraphicData: &oxml.AGraphicData{
				URI:   oxml.TableGraphicDataURI,
				Table: tableDataToOxml(t),
			},
		},
	}

	return gf
}

// tableDataToOxml converts Table data to oxml.ATable.
func tableDataToOxml(t *Table) *oxml.ATable {
	// Ensure gridSpan/rowSpan covered cells carry their hMerge/vMerge flags so
	// the emitted grid is valid (C310).
	t.normalizeMergeCells()

	tbl := &oxml.ATable{
		TblPr: &oxml.ATblPr{
			FirstRow:     t.firstRow,
			FirstCol:     t.firstCol,
			LastRow:      t.lastRow,
			LastCol:      t.lastCol,
			BandRow:      t.bandRow,
			BandCol:      t.bandCol,
			TableStyleId: t.tableStyleID,
		},
		TblGrid: &oxml.ATblGrid{
			GridCol: make([]*oxml.AGridCol, len(t.colWidths)),
		},
		Tr: make([]*oxml.ATr, len(t.rows)),
	}

	// Set column widths
	for i, w := range t.colWidths {
		tbl.TblGrid.GridCol[i] = &oxml.AGridCol{W: int64(w)}
	}

	// Convert rows
	for i, row := range t.rows {
		rowH := int64(row.height)
		tr := &oxml.ATr{
			H:  &rowH,
			Tc: make([]*oxml.ATc, len(row.cells)),
		}

		for j, cell := range row.cells {
			tc := &oxml.ATc{}

			// Set cell properties
			if cell.fill != nil || cell.vertAlign != "" ||
				cell.borderLeft != nil || cell.borderRight != nil ||
				cell.borderTop != nil || cell.borderBottom != nil ||
				cell.margins != nil {
				tc.TcPr = &oxml.ATcPr{}
				if cell.vertAlign != "" {
					tc.TcPr.Anchor = string(cell.vertAlign)
				}
				applyCellMargins(tc.TcPr, cell)
				tc.TcPr.LnL = tableBorderToLn(cell.borderLeft)
				tc.TcPr.LnR = tableBorderToLn(cell.borderRight)
				tc.TcPr.LnT = tableBorderToLn(cell.borderTop)
				tc.TcPr.LnB = tableBorderToLn(cell.borderBottom)
				if cell.fill != nil {
					tc.TcPr.SolidFill = colorToOxml(cell.fill)
				}
			}

			// Set row/col span
			if cell.rowSpan > 1 {
				tc.RowSpan = cell.rowSpan
			}
			if cell.colSpan > 1 {
				tc.GridSpan = cell.colSpan
			}
			tc.HMerge = cell.hMerge
			tc.VMerge = cell.vMerge

			// Convert text
			if cell.textFrame != nil {
				tc.TxBody = textFrameToOxml(cell.textFrame)
			}

			tr.Tc[j] = tc
			cell.sourceTc = tc
		}

		tbl.Tr[i] = tr
		row.sourceTr = tr
	}

	return tbl
}

// regenerateTableNode rebuilds the a:tbl from the domain model after a
// structural change (rows/columns added or removed), carrying parsed content
// over for surviving rows and cells: their tcPr (margins, borders, fills the
// domain does not track per edge) and, when the cell text was not edited,
// their txBody are reused verbatim, and the table keeps its tableStyleId.
// Cells the caller explicitly restyled get those edits applied on top of the
// parsed properties.
func regenerateTableNode(t *Table, old *oxml.ATable) *oxml.ATable {
	// Capture the parsed source nodes before tableDataToOxml re-points every
	// row/cell at its freshly built node.
	oldTr := make([]*oxml.ATr, len(t.rows))
	oldTc := make([][]*oxml.ATc, len(t.rows))
	for i, row := range t.rows {
		oldTr[i] = row.sourceTr
		oldTc[i] = make([]*oxml.ATc, len(row.cells))
		for j, c := range row.cells {
			oldTc[i][j] = c.sourceTc
		}
	}

	tbl := tableDataToOxml(t)
	// tbl.TblPr.TableStyleId already reflects t.tableStyleID, which was
	// materialized from the source table (or overridden via SetStyleID), so the
	// style reference is carried over without re-reading the old node.
	if old != nil && old.TblGrid != nil && tbl.TblGrid != nil &&
		len(old.TblGrid.GridCol) == len(tbl.TblGrid.GridCol) {
		for i, gc := range tbl.TblGrid.GridCol {
			gc.ExtLst = old.TblGrid.GridCol[i].ExtLst
		}
	}

	for i, tr := range tbl.Tr {
		if src := oldTr[i]; src != nil {
			tr.ExtLst = src.ExtLst
		}
		for j, tc := range tr.Tc {
			src := oldTc[i][j]
			if src == nil {
				continue // new cell: keep the generated node
			}
			cell := t.rows[i].cells[j]
			tc.TcPr = src.TcPr
			if cell.dirty {
				applyCellProps(tc, cell)
			}
			tc.TxBody = src.TxBody
			if cell.textFrame != nil && cell.textFrame.isDirty() {
				updateTxBody(&tc.TxBody, cell.textFrame)
			}
		}
	}
	return tbl
}

// tableBorderToLn converts a domain TableBorder to a dml.Ln for a cell edge.
func tableBorderToLn(b *TableBorder) *dml.Ln {
	if b == nil {
		return nil
	}
	ln := &dml.Ln{}
	if b.Width > 0 {
		w := int64(b.Width)
		ln.W = &w
	}
	switch b.Style {
	case BorderStyleNone:
		// An explicit "no border" — emit a line with no fill.
		ln.NoFill = &dml.NoFillXML{}
		return ln
	case BorderStyleDashed:
		ln.PrstDash = &dml.PrstDash{Val: "dash"}
	case BorderStyleDotted:
		ln.PrstDash = &dml.PrstDash{Val: "dot"}
	case BorderStyleDouble:
		ln.Cmpd = "dbl"
	}
	ln.SolidFill = colorToOxml(&b.Color)
	return ln
}

// pictureToOxml converts a Picture to oxml.Picture.
func pictureToOxml(p *Picture, id uint32) *oxml.Picture {
	name := p.Name()
	if name == "" {
		name = "Picture"
	}

	x, y := p.Position()
	w, h := p.Size()

	pic := &oxml.Picture{
		NvPicPr: &oxml.NvPicPr{
			CNvPr: &dml.CNvPr{
				Id:    id,
				Name:  name,
				Descr: p.description,
			},
			CNvPicPr: &dml.CNvPicPr{
				PicLocks: &dml.PicLocks{NoChangeAspect: true},
			},
			NvPr: &oxml.NvPr{},
		},
		BlipFill: &dml.BlipFill{
			Blip: &dml.Blip{
				// The embed reference will be set when saving with relationships
				Embed: p.relID,
			},
			Stretch: &dml.Stretch{
				FillRect: &dml.RelRect{},
			},
		},
		SpPr: &dml.SpPr{
			Xfrm: &dml.Xfrm{
				Off: &dml.OffXML{X: int64(x), Y: int64(y)},
				Ext: &dml.ExtXML{Cx: int64(w), Cy: int64(h)},
			},
			PrstGeom: &dml.PrstGeom{
				Prst:  "rect",
				AvLst: &dml.AvLst{},
			},
		},
	}

	if p.hyperlink != nil {
		pic.NvPicPr.CNvPr.HlinkClick = hyperlinkToXML(p.hyperlink)
	}

	// Apply cropping if set
	if p.cropLeft > 0 || p.cropTop > 0 || p.cropRight > 0 || p.cropBottom > 0 {
		pic.BlipFill.SrcRect = &dml.SrcRect{
			L: dml.NewPercentage(int32(p.cropLeft * 100000)),
			T: dml.NewPercentage(int32(p.cropTop * 100000)),
			R: dml.NewPercentage(int32(p.cropRight * 100000)),
			B: dml.NewPercentage(int32(p.cropBottom * 100000)),
		}
	}

	return pic
}

// Duplicate creates a copy of the slide and adds it after this slide. It
// returns nil when called on a handle that was already removed (C302), rather
// than duplicating whatever slide now sits at the freed index.
//
// Parts that ECMA models as belonging to one slide are copied, not shared: the
// notes slide, and the legacy and modern comment parts — the modern thread's
// pc:sldMk anchor is rewritten to the duplicate's slide id, so the copied thread
// belongs to the slide it now lives on rather than still naming the source
// (C414). Editing either slide's notes or comments therefore leaves the other
// alone.
//
// Everything else the slide references is shared with the original: images,
// media, charts, SmartArt (diagram data/layout/colors/drawing) and embedded OLE
// objects are pointed at by both slides' relationships. That is valid OPC — a
// part may be the target of any number of relationships — and it keeps a
// duplicate from doubling the package size for content neither slide will
// diverge on. It is also currently unobservable through this API: Charts() and
// the SmartArt/OLE accessors return parsed snapshots with no write-back, so
// there is no way to mutate one slide's copy. PowerPoint, by contrast, deep
// copies these on its own duplicate command, so a deck round-tripped through
// this library and then edited in PowerPoint may diverge from one edited here.
func (s *Slide) Duplicate() *Slide {
	if s.presentation == nil || s.index < 0 {
		return nil
	}
	if s.shapesModified || s.hasDirtyShapes() {
		s.syncShapesToXML()
	}
	// Embed any pending image data now, before the XML snapshot below: images
	// are normally embedded at save (processPendingImages), so duplicating an
	// unsaved slide with an added picture would otherwise snapshot a blip with
	// no r:embed and no image relationship, and the duplicate would render
	// blank (C256, the image analogue of the C193 autoplay-timing fix). This
	// embeds into the source slide too, which is correct — its own save then
	// finds nothing pending. Best-effort: a real failure surfaces at save.
	_ = s.processPendingImages()
	// Build any pending auto-play timing tree now, before the XML snapshot
	// below: timing is normally built at save, so duplicating an unsaved
	// slide with auto-play media would otherwise snapshot a tree-less slide
	// and the duplicate would silently lose autoplay (C193). The copied tree
	// targets the same shape ids the copied shapes carry, so it is valid for
	// the duplicate as-is.
	s.applyMediaTiming()
	s.applyAnimations()
	// Serialize any deferred notes/comment edit now, for the same reason: the
	// notes slide and comment threads are copied below as bytes, so an edit
	// still sitting in a model would not be in the copy. Best-effort like the
	// image embed above — a part that cannot be serialized keeps its dirty flag
	// and fails the save that follows.
	s.presentation.flushBestEffort()

	// AddSlide assigned the duplicate its own part name.
	newSlide := s.presentation.AddSlide()
	newSlide.layout = s.layout

	// Copy slide XML and slide-level relationships so the duplicate remains
	// self-contained. Accessing s.sx() materializes the source (a duplicate of a
	// never-touched slide still needs its content copied).
	if src := s.sx(); src != nil {
		if data, err := marshalSlide(src); err == nil {
			var copyXML oxml.Slide
			if err := xml.Unmarshal(data, &copyXML); err == nil {
				newSlide.sxModel = &copyXML
				newSlide.sxParsed = true
			}
		}
	}
	if s.partName != "" {
		s.presentation.clonePartRelationships(s.partName, newSlide.partName)
		// Give the duplicate its own notes slide rather than sharing the
		// original's (otherwise editing one slide's notes changes the other).
		s.presentation.deepCloneNotesSlide(newSlide.partName)
		// Same for comments, which ECMA also models per slide — and whose modern
		// form additionally records which slide the thread hangs off (C414).
		s.presentation.deepCloneCommentParts(newSlide.partName, s.id, newSlide.id)
		// The anchor retarget above is a model edit made after the flush that
		// preceded the copy, so it needs one of its own to reach the copied
		// part's bytes. Same best-effort contract.
		s.presentation.flushBestEffort()
	}
	if newSlide.sxModel == nil {
		newSlide.sxModel = newSlideXML()
		newSlide.sxParsed = true
	}
	newSlide.materializeShapes()

	// Move to position after original
	_ = s.presentation.MoveSlide(newSlide.index, s.index+1)

	return newSlide
}

// Delete removes this slide from the presentation. It returns ErrInvalidSlide
// when called on a handle that was already removed (a second Delete, C302),
// rather than deleting whatever slide now sits at the freed index.
func (s *Slide) Delete() error {
	if s.presentation == nil || s.index < 0 {
		return ErrInvalidSlide
	}
	return s.presentation.RemoveSlide(s.index)
}
